[package]
name = "typegraph"
version.workspace = true
edition.workspace = true

[dependencies]
tg_schema.workspace = true
serde.workspace = true
serde_json.workspace = true
enum_dispatch.workspace = true
indexmap.workspace = true
paste.workspace = true
color-eyre.workspace = true
tracing.workspace = true

[dev-dependencies]
insta.workspace = true
