[package]
name = "typegraph"
version.workspace = true
edition.workspace = true

# this allows us to exclude the rust files
# from the dockerfile while keeping the Cargo.toml
# for cargo chef. Useful to improve cache hit in docker
[lib]
path = "src/lib.rs"

[dependencies]
tg_schema.workspace = true
serde.workspace = true
serde_json.workspace = true
enum_dispatch.workspace = true
indexmap.workspace = true
paste.workspace = true
color-eyre.workspace = true
tracing.workspace = true
derive_more.workspace = true

[dev-dependencies]
insta.workspace = true
