from typegraph import t

class TypeList:
    Order: t.typedef = ...
    Customer: t.typedef = ...
    Address: t.typedef = ...
    Category: t.typedef = ...
    User: t.typedef = ...
    Tag: t.typedef = ...
    Pet: t.typedef = ...
    ApiResponse: t.typedef = ...

class FuncList:
    updatePet: t.func = ...
    addPet: t.func = ...
    findPetsByStatus: t.func = ...
    findPetsByTags: t.func = ...
    getPetById: t.func = ...
    updatePetWithForm: t.func = ...
    deletePet: t.func = ...
    getInventory: t.func = ...
    placeOrder: t.func = ...
    getOrderById: t.func = ...
    deleteOrder: t.func = ...
    createUser: t.func = ...
    loginUser: t.func = ...
    logoutUser: t.func = ...
    getUserByName: t.func = ...
    deleteUser: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_petstore() -> Import: ...
