package.name = "metagen_fdk_rs_static"
package.edition = "2021"
package.version = "0.0.1"

[lib]
path = "lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
metagen-client = { workspace = true }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
wit-bindgen.workspace = true
