package.name = "metagen_fdk_rs_static"
package.edition = "2021"
package.version = "0.0.1"

[lib]
path = "lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
metagen-client = { workspace = true, optional = true }
anyhow = "1.0.89"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
wit-bindgen = "0.34.0"
