changelog:
  exclude:
    authors:
      - octocat
      - dependabot
  categories:
    - title: Breaking changes 🛠
      labels:
        - breaking-change
    - title: Documentation improvements 📖
      labels:
        - documentation
    - title: Bug fixes 🐛
      labels:
        - bug
    - title: New features 🎉
      labels:
        - "*"
