from typegraph.runtimes.http import HTTPRuntime
from typegraph.importers.base.importer import Import
from typegraph import t

# skip:start
from typegraph import TypeGraph
from typegraph.importers.google_discovery import GoogleDiscoveryImporter

discovery = "https://fcm.googleapis.com/$discovery/rest?version=v1"

GoogleDiscoveryImporter(
    "googleapi", url="https://fcm.googleapis.com/$discovery/rest?version=v1"
).imp(False)


# Function generated by GoogleDiscoveryImporter. Do not change.
def import_googleapi():
    googleapi = HTTPRuntime("https://fcm.googleapis.com/")

    renames = {
        "ErrorResponse": "_googleapi_1_ErrorResponse",
        "ColorIn": "_googleapi_2_ColorIn",
        "ColorOut": "_googleapi_3_ColorOut",
        "NotificationIn": "_googleapi_4_NotificationIn",
        "NotificationOut": "_googleapi_5_NotificationOut",
        "AndroidFcmOptionsIn": "_googleapi_6_AndroidFcmOptionsIn",
        "AndroidFcmOptionsOut": "_googleapi_7_AndroidFcmOptionsOut",
        "MessageIn": "_googleapi_8_MessageIn",
        "MessageOut": "_googleapi_9_MessageOut",
        "ApnsFcmOptionsIn": "_googleapi_10_ApnsFcmOptionsIn",
        "ApnsFcmOptionsOut": "_googleapi_11_ApnsFcmOptionsOut",
        "SendMessageRequestIn": "_googleapi_12_SendMessageRequestIn",
        "SendMessageRequestOut": "_googleapi_13_SendMessageRequestOut",
        "AndroidConfigIn": "_googleapi_14_AndroidConfigIn",
        "AndroidConfigOut": "_googleapi_15_AndroidConfigOut",
        "WebpushConfigIn": "_googleapi_16_WebpushConfigIn",
        "WebpushConfigOut": "_googleapi_17_WebpushConfigOut",
        "LightSettingsIn": "_googleapi_18_LightSettingsIn",
        "LightSettingsOut": "_googleapi_19_LightSettingsOut",
        "FcmOptionsIn": "_googleapi_20_FcmOptionsIn",
        "FcmOptionsOut": "_googleapi_21_FcmOptionsOut",
        "ApnsConfigIn": "_googleapi_22_ApnsConfigIn",
        "ApnsConfigOut": "_googleapi_23_ApnsConfigOut",
        "AndroidNotificationIn": "_googleapi_24_AndroidNotificationIn",
        "AndroidNotificationOut": "_googleapi_25_AndroidNotificationOut",
        "WebpushFcmOptionsIn": "_googleapi_26_WebpushFcmOptionsIn",
        "WebpushFcmOptionsOut": "_googleapi_27_WebpushFcmOptionsOut",
    }

    types = {}
    types["ErrorResponse"] = t.struct(
        {"code": t.integer(), "message": t.string(), "status": t.string()}
    ).named(renames["ErrorResponse"])
    types["ColorIn"] = t.struct(
        {
            "alpha": t.number().optional(),
            "red": t.number().optional(),
            "green": t.number().optional(),
            "blue": t.number().optional(),
        }
    ).named(renames["ColorIn"])
    types["ColorOut"] = t.struct(
        {
            "alpha": t.number().optional(),
            "red": t.number().optional(),
            "green": t.number().optional(),
            "blue": t.number().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ColorOut"])
    types["NotificationIn"] = t.struct(
        {
            "image": t.string().optional(),
            "body": t.string().optional(),
            "title": t.string().optional(),
        }
    ).named(renames["NotificationIn"])
    types["NotificationOut"] = t.struct(
        {
            "image": t.string().optional(),
            "body": t.string().optional(),
            "title": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["NotificationOut"])
    types["AndroidFcmOptionsIn"] = t.struct(
        {"analyticsLabel": t.string().optional()}
    ).named(renames["AndroidFcmOptionsIn"])
    types["AndroidFcmOptionsOut"] = t.struct(
        {
            "analyticsLabel": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AndroidFcmOptionsOut"])
    # skip:end
    # ...
    types["MessageIn"] = t.struct(
        {
            "notification": t.proxy(renames["NotificationIn"]).optional(),
            "condition": t.string().optional(),
            "webpush": t.proxy(renames["WebpushConfigIn"]).optional(),
            "name": t.string().optional(),
            "topic": t.string().optional(),
            "android": t.proxy(renames["AndroidConfigIn"]).optional(),
            "token": t.string().optional(),
            "fcmOptions": t.proxy(renames["FcmOptionsIn"]).optional(),
            "data": t.struct({}).optional(),
            "apns": t.proxy(renames["ApnsConfigIn"]).optional(),
        }
    ).named(renames["MessageIn"])
    # ...
    # skip:start
    types["MessageOut"] = t.struct(
        {
            "notification": t.proxy(renames["NotificationOut"]).optional(),
            "condition": t.string().optional(),
            "webpush": t.proxy(renames["WebpushConfigOut"]).optional(),
            "name": t.string().optional(),
            "topic": t.string().optional(),
            "android": t.proxy(renames["AndroidConfigOut"]).optional(),
            "token": t.string().optional(),
            "fcmOptions": t.proxy(renames["FcmOptionsOut"]).optional(),
            "data": t.struct({}).optional(),
            "apns": t.proxy(renames["ApnsConfigOut"]).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["MessageOut"])
    types["ApnsFcmOptionsIn"] = t.struct(
        {"image": t.string().optional(), "analyticsLabel": t.string().optional()}
    ).named(renames["ApnsFcmOptionsIn"])
    types["ApnsFcmOptionsOut"] = t.struct(
        {
            "image": t.string().optional(),
            "analyticsLabel": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ApnsFcmOptionsOut"])
    types["SendMessageRequestIn"] = t.struct(
        {
            "validateOnly": t.boolean().optional(),
            "message": t.proxy(renames["MessageIn"]),
        }
    ).named(renames["SendMessageRequestIn"])
    types["SendMessageRequestOut"] = t.struct(
        {
            "validateOnly": t.boolean().optional(),
            "message": t.proxy(renames["MessageOut"]),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SendMessageRequestOut"])
    types["AndroidConfigIn"] = t.struct(
        {
            "ttl": t.string().optional(),
            "data": t.struct({}).optional(),
            "priority": t.string().optional(),
            "restrictedPackageName": t.string().optional(),
            "fcmOptions": t.proxy(renames["AndroidFcmOptionsIn"]).optional(),
            "directBootOk": t.boolean().optional(),
            "notification": t.proxy(renames["AndroidNotificationIn"]).optional(),
            "collapseKey": t.string().optional(),
        }
    ).named(renames["AndroidConfigIn"])
    types["AndroidConfigOut"] = t.struct(
        {
            "ttl": t.string().optional(),
            "data": t.struct({}).optional(),
            "priority": t.string().optional(),
            "restrictedPackageName": t.string().optional(),
            "fcmOptions": t.proxy(renames["AndroidFcmOptionsOut"]).optional(),
            "directBootOk": t.boolean().optional(),
            "notification": t.proxy(renames["AndroidNotificationOut"]).optional(),
            "collapseKey": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AndroidConfigOut"])
    types["WebpushConfigIn"] = t.struct(
        {
            "data": t.struct({}).optional(),
            "headers": t.struct({}).optional(),
            "fcmOptions": t.proxy(renames["WebpushFcmOptionsIn"]).optional(),
            "notification": t.struct({}).optional(),
        }
    ).named(renames["WebpushConfigIn"])
    types["WebpushConfigOut"] = t.struct(
        {
            "data": t.struct({}).optional(),
            "headers": t.struct({}).optional(),
            "fcmOptions": t.proxy(renames["WebpushFcmOptionsOut"]).optional(),
            "notification": t.struct({}).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["WebpushConfigOut"])
    types["LightSettingsIn"] = t.struct(
        {
            "lightOnDuration": t.string(),
            "color": t.proxy(renames["ColorIn"]),
            "lightOffDuration": t.string(),
        }
    ).named(renames["LightSettingsIn"])
    types["LightSettingsOut"] = t.struct(
        {
            "lightOnDuration": t.string(),
            "color": t.proxy(renames["ColorOut"]),
            "lightOffDuration": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["LightSettingsOut"])
    types["FcmOptionsIn"] = t.struct({"analyticsLabel": t.string().optional()}).named(
        renames["FcmOptionsIn"]
    )
    types["FcmOptionsOut"] = t.struct(
        {
            "analyticsLabel": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["FcmOptionsOut"])
    types["ApnsConfigIn"] = t.struct(
        {
            "headers": t.struct({}).optional(),
            "fcmOptions": t.proxy(renames["ApnsFcmOptionsIn"]).optional(),
            "payload": t.struct({}).optional(),
        }
    ).named(renames["ApnsConfigIn"])
    types["ApnsConfigOut"] = t.struct(
        {
            "headers": t.struct({}).optional(),
            "fcmOptions": t.proxy(renames["ApnsFcmOptionsOut"]).optional(),
            "payload": t.struct({}).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ApnsConfigOut"])
    types["AndroidNotificationIn"] = t.struct(
        {
            "titleLocKey": t.string().optional(),
            "clickAction": t.string().optional(),
            "icon": t.string().optional(),
            "localOnly": t.boolean().optional(),
            "image": t.string().optional(),
            "notificationPriority": t.string().optional(),
            "defaultLightSettings": t.boolean().optional(),
            "vibrateTimings": t.array(t.string()).optional(),
            "titleLocArgs": t.array(t.string()).optional(),
            "color": t.string().optional(),
            "visibility": t.string().optional(),
            "sticky": t.boolean().optional(),
            "eventTime": t.string().optional(),
            "defaultSound": t.boolean().optional(),
            "notificationCount": t.integer().optional(),
            "defaultVibrateTimings": t.boolean().optional(),
            "lightSettings": t.proxy(renames["LightSettingsIn"]).optional(),
            "title": t.string().optional(),
            "bypassProxyNotification": t.boolean().optional(),
            "ticker": t.string().optional(),
            "channelId": t.string().optional(),
            "bodyLocKey": t.string().optional(),
            "tag": t.string().optional(),
            "bodyLocArgs": t.array(t.string()).optional(),
            "sound": t.string().optional(),
            "body": t.string().optional(),
        }
    ).named(renames["AndroidNotificationIn"])
    types["AndroidNotificationOut"] = t.struct(
        {
            "titleLocKey": t.string().optional(),
            "clickAction": t.string().optional(),
            "icon": t.string().optional(),
            "localOnly": t.boolean().optional(),
            "image": t.string().optional(),
            "notificationPriority": t.string().optional(),
            "defaultLightSettings": t.boolean().optional(),
            "vibrateTimings": t.array(t.string()).optional(),
            "titleLocArgs": t.array(t.string()).optional(),
            "color": t.string().optional(),
            "visibility": t.string().optional(),
            "sticky": t.boolean().optional(),
            "eventTime": t.string().optional(),
            "defaultSound": t.boolean().optional(),
            "notificationCount": t.integer().optional(),
            "defaultVibrateTimings": t.boolean().optional(),
            "lightSettings": t.proxy(renames["LightSettingsOut"]).optional(),
            "title": t.string().optional(),
            "bypassProxyNotification": t.boolean().optional(),
            "ticker": t.string().optional(),
            "channelId": t.string().optional(),
            "bodyLocKey": t.string().optional(),
            "tag": t.string().optional(),
            "bodyLocArgs": t.array(t.string()).optional(),
            "sound": t.string().optional(),
            "body": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AndroidNotificationOut"])
    types["WebpushFcmOptionsIn"] = t.struct(
        {"link": t.string().optional(), "analyticsLabel": t.string().optional()}
    ).named(renames["WebpushFcmOptionsIn"])
    types["WebpushFcmOptionsOut"] = t.struct(
        {
            "link": t.string().optional(),
            "analyticsLabel": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["WebpushFcmOptionsOut"])

    functions = {}
    functions["projectsMessagesSend"] = googleapi.post(
        "v1/{parent}/messages:send",
        t.struct(
            {
                "parent": t.string(),
                "validateOnly": t.boolean().optional(),
                "message": t.proxy(renames["MessageIn"]),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["MessageOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )

    return Import(
        importer="googleapi", renames=renames, types=types, functions=functions
    )


with TypeGraph(
    "fcm-google",
    cors=TypeGraph.Cors(allow_origin=["https://metatype.dev", "http://localhost:3000"]),
) as g:
    pass
