[package]
name = "tg_schema"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["preserve_order"] }
serde_with.workspace = true
indexmap.workspace = true
ordered-float.workspace = true
