services:
  envoy:
    image: envoyproxy/envoy:v1.26-latest
    restart: always
    ports:
      - "9901:9901"
      - "7890:10000"
    volumes:
      - ../envoy.yaml:/etc/envoy/envoy.yaml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: bitnami/redis:7.0
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password

  verdaccio:
    image: verdaccio/verdaccio
    restart: always
    ports:
      - "4873:4873"
    volumes:
      - ../verdaccio/:/verdaccio/conf/:ro
