services:
  haproxy:
    image: haproxy:2.5
    restart: always
    ports:
      - "7890:8000"
    volumes:
      - ../haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    command: --requirepass password
