from typegraph import policies
from typegraph import t
from typegraph import TypeGraph
from typegraph.importers.base.importer import Import
from typegraph.importers.openapi import OpenApiImporter
from typegraph.runtimes.http import HTTPRuntime


OpenApiImporter(
    "devto",
    url="https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/dev.to/0.9.7/openapi.yaml",
    keep_names=["Listing", "ListingCategory"],
).imp(False)


# Function generated by OpenApiImporter. Do not change.
def import_devto():
    devto = HTTPRuntime("https://dev.to/api")

    renames = {
        "APIError": "_devto_1_APIError",
        "ArticleCreate": "_devto_2_ArticleCreate",
        "ArticleFlareTag": "_devto_3_ArticleFlareTag",
        "ArticleIndex": "_devto_4_ArticleIndex",
        "ArticleMe": "_devto_5_ArticleMe",
        "ArticleShow": "_devto_6_ArticleShow",
        "ArticleUpdate": "_devto_7_ArticleUpdate",
        "ArticleVideo": "_devto_8_ArticleVideo",
        "Comment": "_devto_9_Comment",
        "FollowedTag": "_devto_10_FollowedTag",
        "Follower": "_devto_11_Follower",
        "Listing": "Listing",
        "ListingCategory": "ListingCategory",
        "ListingCreate": "_devto_14_ListingCreate",
        "ListingUpdate": "_devto_15_ListingUpdate",
        "Organization": "_devto_16_Organization",
        "PodcastEpisode": "_devto_17_PodcastEpisode",
        "ProfileImage": "_devto_18_ProfileImage",
        "ReadingList": "_devto_19_ReadingList",
        "SharedOrganization": "_devto_20_SharedOrganization",
        "SharedUser": "_devto_21_SharedUser",
        "Tag": "_devto_22_Tag",
        "User": "_devto_23_User",
        "WebhookCreate": "_devto_24_WebhookCreate",
        "WebhookIndex": "_devto_25_WebhookIndex",
        "WebhookShow": "_devto_26_WebhookShow",
    }

    types = {}
    types["APIError"] = t.struct({"error": t.string(), "status": t.integer()}).named(
        "_devto_1_APIError"
    )
    types["ArticleCreate"] = t.struct(
        {
            "article": t.struct(
                {
                    "body_markdown": t.string(),
                    "canonical_url": t.string(),
                    "description": t.string(),
                    "main_image": t.string(),
                    "organization_id": t.integer(),
                    "published": t.boolean(),
                    "series": t.string(),
                    "tags": t.array(t.string()),
                    "title": t.string(),
                }
            )
        }
    ).named("_devto_2_ArticleCreate")
    types["ArticleFlareTag"] = t.struct(
        {"bg_color_hex": t.string(), "name": t.string(), "text_color_hex": t.string()}
    ).named("_devto_3_ArticleFlareTag")
    types["ArticleIndex"] = t.struct(
        {
            "canonical_url": t.string(),
            "comments_count": t.integer(),
            "cover_image": t.string(),
            "created_at": t.string(),
            "crossposted_at": t.string(),
            "description": t.string(),
            "edited_at": t.string(),
            "flare_tag": t.proxy(renames["ArticleFlareTag"]),
            "id": t.integer(),
            "last_comment_at": t.string(),
            "organization": t.proxy(renames["SharedOrganization"]),
            "path": t.string(),
            "positive_reactions_count": t.integer(),
            "public_reactions_count": t.integer(),
            "published_at": t.string(),
            "published_timestamp": t.string(),
            "readable_publish_date": t.string(),
            "reading_time_minutes": t.integer(),
            "slug": t.string(),
            "social_image": t.string(),
            "tag_list": t.array(t.string()),
            "tags": t.string(),
            "title": t.string(),
            "type_of": t.string(),
            "url": t.string(),
            "user": t.proxy(renames["SharedUser"]),
        }
    ).named("_devto_4_ArticleIndex")
    types["ArticleMe"] = t.struct(
        {
            "body_markdown": t.string(),
            "canonical_url": t.string(),
            "comments_count": t.integer(),
            "cover_image": t.string(),
            "description": t.string(),
            "flare_tag": t.proxy(renames["ArticleFlareTag"]),
            "id": t.integer(),
            "organization": t.proxy(renames["SharedOrganization"]),
            "page_views_count": t.integer(),
            "path": t.string(),
            "positive_reactions_count": t.integer(),
            "public_reactions_count": t.integer(),
            "published": t.boolean(),
            "published_at": t.string(),
            "published_timestamp": t.string(),
            "reading_time_minutes": t.integer(),
            "slug": t.string(),
            "tag_list": t.array(t.string()),
            "title": t.string(),
            "type_of": t.string(),
            "url": t.string(),
            "user": t.proxy(renames["SharedUser"]),
        }
    ).named("_devto_5_ArticleMe")
    types["ArticleShow"] = t.struct(
        {
            "body_html": t.string(),
            "body_markdown": t.string(),
            "canonical_url": t.string(),
            "comments_count": t.integer(),
            "cover_image": t.string(),
            "created_at": t.string(),
            "crossposted_at": t.string(),
            "description": t.string(),
            "edited_at": t.string(),
            "flare_tag": t.proxy(renames["ArticleFlareTag"]),
            "id": t.integer(),
            "last_comment_at": t.string(),
            "organization": t.proxy(renames["SharedOrganization"]),
            "path": t.string(),
            "positive_reactions_count": t.integer(),
            "public_reactions_count": t.integer(),
            "published_at": t.string(),
            "published_timestamp": t.string(),
            "readable_publish_date": t.string(),
            "reading_time_minutes": t.integer(),
            "slug": t.string(),
            "social_image": t.string(),
            "tag_list": t.string(),
            "tags": t.array(t.string()),
            "title": t.string(),
            "type_of": t.string(),
            "url": t.string(),
            "user": t.proxy(renames["SharedUser"]),
        }
    ).named("_devto_6_ArticleShow")
    types["ArticleUpdate"] = t.struct(
        {
            "article": t.struct(
                {
                    "body_markdown": t.string(),
                    "canonical_url": t.string(),
                    "description": t.string(),
                    "main_image": t.string(),
                    "organization_id": t.integer(),
                    "published": t.boolean(),
                    "series": t.string(),
                    "tags": t.array(t.string()),
                    "title": t.string(),
                }
            )
        }
    ).named("_devto_7_ArticleUpdate")
    types["ArticleVideo"] = t.struct(
        {
            "cloudinary_video_url": t.string(),
            "id": t.integer(),
            "path": t.string(),
            "title": t.string(),
            "type_of": t.string(),
            "user": t.struct({"name": t.string()}),
            "user_id": t.integer(),
            "video_duration_in_minutes": t.string(),
            "video_source_url": t.string(),
        }
    ).named("_devto_8_ArticleVideo")
    types["Comment"] = t.struct(
        {
            "body_html": t.string(),
            "children": t.array(t.proxy(renames["Comment"])),
            "created_at": t.string(),
            "id_code": t.string(),
            "type_of": t.string(),
            "user": t.proxy(renames["SharedUser"]),
        }
    ).named("_devto_9_Comment")
    types["FollowedTag"] = t.struct(
        {"id": t.integer(), "name": t.string(), "points": t.number()}
    ).named("_devto_10_FollowedTag")
    types["Follower"] = t.struct(
        {
            "created_at": t.string(),
            "id": t.integer(),
            "name": t.string(),
            "path": t.string(),
            "profile_image": t.string(),
            "type_of": t.string(),
            "username": t.string(),
        }
    ).named("_devto_11_Follower")
    types["Listing"] = t.struct(
        {
            "body_markdown": t.string(),
            "category": t.proxy(renames["ListingCategory"]),
            "id": t.integer(),
            "organization": t.proxy(renames["SharedOrganization"]),
            "processed_html": t.string(),
            "published": t.boolean(),
            "slug": t.string(),
            "tag_list": t.string(),
            "tags": t.array(t.string()),
            "title": t.string(),
            "type_of": t.string(),
            "user": t.proxy(renames["SharedUser"]),
        }
    ).named("Listing")
    types["ListingCategory"] = t.string().named("ListingCategory")
    types["ListingCreate"] = t.struct(
        {
            "listing": t.struct(
                {
                    "action": t.string(),
                    "body_markdown": t.string(),
                    "category": t.proxy(renames["ListingCategory"]),
                    "contact_via_connect": t.boolean(),
                    "expires_at": t.string(),
                    "location": t.string(),
                    "organization_id": t.integer(),
                    "tag_list": t.string(),
                    "tags": t.array(t.string()),
                    "title": t.string(),
                }
            )
        }
    ).named("_devto_14_ListingCreate")
    types["ListingUpdate"] = t.struct(
        {
            "listing": t.struct(
                {
                    "action": t.string(),
                    "body_markdown": t.string(),
                    "category": t.proxy(renames["ListingCategory"]),
                    "contact_via_connect": t.boolean(),
                    "expires_at": t.string(),
                    "location": t.string(),
                    "tag_list": t.string(),
                    "tags": t.array(t.string()),
                    "title": t.string(),
                }
            )
        }
    ).named("_devto_15_ListingUpdate")
    types["Organization"] = t.struct(
        {
            "github_username": t.string(),
            "joined_at": t.string(),
            "location": t.string(),
            "name": t.string(),
            "profile_image": t.string(),
            "story": t.string(),
            "summary": t.string(),
            "tag_line": t.string(),
            "tech_stack": t.string(),
            "twitter_username": t.string(),
            "type_of": t.string(),
            "url": t.string(),
            "username": t.string(),
        }
    ).named("_devto_16_Organization")
    types["PodcastEpisode"] = t.struct(
        {
            "id": t.integer(),
            "image_url": t.string(),
            "path": t.string(),
            "podcast": t.struct(
                {"image_url": t.string(), "slug": t.string(), "title": t.string()}
            ),
            "title": t.string(),
            "type_of": t.string(),
        }
    ).named("_devto_17_PodcastEpisode")
    types["ProfileImage"] = t.struct(
        {
            "image_of": t.string(),
            "profile_image": t.string(),
            "profile_image_90": t.string(),
            "type_of": t.string(),
        }
    ).named("_devto_18_ProfileImage")
    types["ReadingList"] = t.struct(
        {
            "article": t.proxy(renames["ArticleIndex"]),
            "created_at": t.string(),
            "id": t.integer(),
            "status": t.string(),
            "type_of": t.string(),
        }
    ).named("_devto_19_ReadingList")
    types["SharedOrganization"] = t.struct(
        {
            "name": t.string(),
            "profile_image": t.string(),
            "profile_image_90": t.string(),
            "slug": t.string(),
            "username": t.string(),
        }
    ).named("_devto_20_SharedOrganization")
    types["SharedUser"] = t.struct(
        {
            "github_username": t.string(),
            "name": t.string(),
            "profile_image": t.string(),
            "profile_image_90": t.string(),
            "twitter_username": t.string(),
            "username": t.string(),
            "website_url": t.string(),
        }
    ).named("_devto_21_SharedUser")
    types["Tag"] = t.struct(
        {
            "bg_color_hex": t.string(),
            "id": t.integer(),
            "name": t.string(),
            "text_color_hex": t.string(),
        }
    ).named("_devto_22_Tag")
    types["User"] = t.struct(
        {
            "github_username": t.string(),
            "id": t.integer(),
            "joined_at": t.string(),
            "location": t.string(),
            "name": t.string(),
            "profile_image": t.string(),
            "summary": t.string(),
            "twitter_username": t.string(),
            "type_of": t.string(),
            "username": t.string(),
            "website_url": t.string(),
        }
    ).named("_devto_23_User")
    types["WebhookCreate"] = t.struct(
        {
            "webhook_endpoint": t.struct(
                {
                    "events": t.array(t.string()),
                    "source": t.string(),
                    "target_url": t.string(),
                }
            )
        }
    ).named("_devto_24_WebhookCreate")
    types["WebhookIndex"] = t.struct(
        {
            "created_at": t.string(),
            "events": t.array(t.string()),
            "id": t.integer(),
            "source": t.string(),
            "target_url": t.string(),
            "type_of": t.string(),
        }
    ).named("_devto_25_WebhookIndex")
    types["WebhookShow"] = t.struct(
        {
            "created_at": t.string(),
            "events": t.array(t.string()),
            "id": t.integer(),
            "source": t.string(),
            "target_url": t.string(),
            "type_of": t.string(),
            "user": t.proxy(renames["SharedUser"]),
        }
    ).named("_devto_26_WebhookShow")

    functions = {}
    functions["getArticles"] = devto.get(
        "/articles",
        t.struct(
            {
                "page": t.integer(),
                "per_page": t.integer(),
                "tag": t.string(),
                "tags": t.string(),
                "tags_exclude": t.string(),
                "username": t.string(),
                "state": t.string(),
                "top": t.integer(),
                "collection_id": t.integer(),
            }
        ),
        t.array(t.proxy(renames["ArticleIndex"])),
    )
    functions["createArticle"] = devto.post(
        "/articles",
        t.struct(
            {
                "article": t.struct(
                    {
                        "body_markdown": t.string(),
                        "canonical_url": t.string(),
                        "description": t.string(),
                        "main_image": t.string(),
                        "organization_id": t.integer(),
                        "published": t.boolean(),
                        "series": t.string(),
                        "tags": t.array(t.string()),
                        "title": t.string(),
                    }
                )
            }
        ),
        t.proxy(renames["ArticleShow"]),
        content_type="application/json",
        body_fields=("article",),
    )
    functions["getLatestArticles"] = devto.get(
        "/articles/latest",
        t.struct({"page": t.integer(), "per_page": t.integer()}),
        t.array(t.proxy(renames["ArticleIndex"])),
    )
    functions["getUserArticles"] = devto.get(
        "/articles/me",
        t.struct({"page": t.integer(), "per_page": t.integer()}),
        t.array(t.proxy(renames["ArticleMe"])),
    )
    functions["getUserAllArticles"] = devto.get(
        "/articles/me/all",
        t.struct({"page": t.integer(), "per_page": t.integer()}),
        t.array(t.proxy(renames["ArticleMe"])),
    )
    functions["getUserPublishedArticles"] = devto.get(
        "/articles/me/published",
        t.struct({"page": t.integer(), "per_page": t.integer()}),
        t.array(t.proxy(renames["ArticleMe"])),
    )
    functions["getUserUnpublishedArticles"] = devto.get(
        "/articles/me/unpublished",
        t.struct({"page": t.integer(), "per_page": t.integer()}),
        t.array(t.proxy(renames["ArticleMe"])),
    )
    functions["getArticleById"] = devto.get(
        "/articles/{id}",
        t.struct({"id": t.integer()}),
        t.proxy(renames["ArticleShow"]).optional(),
    )
    functions["updateArticle"] = devto.put(
        "/articles/{id}",
        t.struct(
            {
                "id": t.integer(),
                "article": t.struct(
                    {
                        "body_markdown": t.string(),
                        "canonical_url": t.string(),
                        "description": t.string(),
                        "main_image": t.string(),
                        "organization_id": t.integer(),
                        "published": t.boolean(),
                        "series": t.string(),
                        "tags": t.array(t.string()),
                        "title": t.string(),
                    }
                ),
            }
        ),
        t.proxy(renames["ArticleShow"]),
        content_type="application/json",
        body_fields=("article",),
    )
    functions["getArticleByPath"] = devto.get(
        "/articles/{username}/{slug}",
        t.struct({"username": t.string(), "slug": t.string()}),
        t.proxy(renames["ArticleShow"]).optional(),
    )
    functions["getCommentsByArticleId"] = devto.get(
        "/comments",
        t.struct({"a_id": t.integer(), "p_id": t.integer()}),
        t.array(t.proxy(renames["Comment"])).optional(),
    )
    functions["getCommentById"] = devto.get(
        "/comments/{id}",
        t.struct({"id": t.string()}),
        t.proxy(renames["Comment"]).optional(),
    )
    functions["getFollowers"] = devto.get(
        "/followers/users",
        t.struct({"page": t.integer(), "per_page": t.integer(), "sort": t.string()}),
        t.array(t.proxy(renames["Follower"])),
    )
    functions["getFollowedTags"] = devto.get(
        "/follows/tags",
        t.struct({}),
        t.array(t.proxy(renames["FollowedTag"])),
    )
    functions["getListings"] = devto.get(
        "/listings",
        t.struct(
            {"page": t.integer(), "per_page": t.integer(), "category": t.string()}
        ),
        t.array(t.proxy(renames["Listing"])),
    )
    functions["createListing"] = devto.post(
        "/listings",
        t.struct(
            {
                "listing": t.struct(
                    {
                        "action": t.string(),
                        "body_markdown": t.string(),
                        "category": t.proxy(renames["ListingCategory"]),
                        "contact_via_connect": t.boolean(),
                        "expires_at": t.string(),
                        "location": t.string(),
                        "organization_id": t.integer(),
                        "tag_list": t.string(),
                        "tags": t.array(t.string()),
                        "title": t.string(),
                    }
                )
            }
        ),
        t.proxy(renames["Listing"]),
        content_type="application/json",
        body_fields=("listing",),
    )
    functions["getListingsByCategory"] = devto.get(
        "/listings/category/{category}",
        t.struct(
            {
                "category": t.proxy(renames["ListingCategory"]),
                "page": t.integer(),
                "per_page": t.integer(),
            }
        ),
        t.array(t.proxy(renames["Listing"])),
    )
    functions["getListingById"] = devto.get(
        "/listings/{id}",
        t.struct({"id": t.integer()}),
        t.proxy(renames["Listing"]).optional(),
    )
    functions["updateListing"] = devto.put(
        "/listings/{id}",
        t.struct(
            {
                "id": t.integer(),
                "listing": t.struct(
                    {
                        "action": t.string(),
                        "body_markdown": t.string(),
                        "category": t.proxy(renames["ListingCategory"]),
                        "contact_via_connect": t.boolean(),
                        "expires_at": t.string(),
                        "location": t.string(),
                        "tag_list": t.string(),
                        "tags": t.array(t.string()),
                        "title": t.string(),
                    }
                ),
            }
        ),
        t.proxy(renames["ArticleShow"]),
        content_type="application/json",
        body_fields=("listing",),
    )
    functions["getOrganization"] = devto.get(
        "/organizations/{username}",
        t.struct({"username": t.string()}),
        t.proxy(renames["Organization"]).optional(),
    )
    functions["getOrgArticles"] = devto.get(
        "/organizations/{username}/articles",
        t.struct(
            {"username": t.string(), "page": t.integer(), "per_page": t.integer()}
        ),
        t.array(t.proxy(renames["ArticleIndex"])).optional(),
    )
    functions["getOrgListings"] = devto.get(
        "/organizations/{username}/listings",
        t.struct(
            {
                "username": t.string(),
                "page": t.integer(),
                "per_page": t.integer(),
                "category": t.string(),
            }
        ),
        t.array(
            t.struct(
                {
                    "body_markdown": t.string(),
                    "category": t.proxy(renames["ListingCategory"]),
                    "id": t.integer(),
                    "organization": t.proxy(renames["SharedOrganization"]),
                    "processed_html": t.string(),
                    "published": t.boolean(),
                    "slug": t.string(),
                    "tag_list": t.string(),
                    "tags": t.array(t.string()),
                    "title": t.string(),
                    "type_of": t.string(),
                    "user": t.proxy(renames["SharedUser"]),
                }
            )
        ).optional(),
    )
    functions["getOrgUsers"] = devto.get(
        "/organizations/{username}/users",
        t.struct(
            {"username": t.string(), "page": t.integer(), "per_page": t.integer()}
        ),
        t.array(t.proxy(renames["User"])).optional(),
    )
    functions["getPodcastEpisodes"] = devto.get(
        "/podcast_episodes",
        t.struct(
            {"page": t.integer(), "per_page": t.integer(), "username": t.string()}
        ),
        t.array(t.proxy(renames["PodcastEpisode"])).optional(),
    )
    functions["getProfileImage"] = devto.get(
        "/profile_images/{username}",
        t.struct({"username": t.string()}),
        t.proxy(renames["ProfileImage"]).optional(),
    )
    functions["getReadinglist"] = devto.get(
        "/readinglist",
        t.struct({"page": t.integer(), "per_page": t.integer()}),
        t.array(t.proxy(renames["ReadingList"])),
    )
    functions["getTags"] = devto.get(
        "/tags",
        t.struct({"page": t.integer(), "per_page": t.integer()}),
        t.array(t.proxy(renames["Tag"])),
    )
    functions["getUserMe"] = devto.get(
        "/users/me",
        t.struct({}),
        t.proxy(renames["User"]),
    )
    functions["getUser"] = devto.get(
        "/users/{id}",
        t.struct({"id": t.string(), "url": t.string()}),
        t.proxy(renames["User"]).optional(),
    )
    functions["getArticlesWithVideo"] = devto.get(
        "/videos",
        t.struct({"page": t.integer(), "per_page": t.integer()}),
        t.array(t.proxy(renames["ArticleVideo"])),
    )
    functions["getWebhooks"] = devto.get(
        "/webhooks",
        t.struct({}),
        t.array(t.proxy(renames["WebhookIndex"])),
    )
    functions["createWebhook"] = devto.post(
        "/webhooks",
        t.struct(
            {
                "webhook_endpoint": t.struct(
                    {
                        "events": t.array(t.string()),
                        "source": t.string(),
                        "target_url": t.string(),
                    }
                )
            }
        ),
        t.proxy(renames["WebhookShow"]),
        content_type="application/json",
        body_fields=("webhook_endpoint",),
    )
    functions["deleteWebhook"] = devto.delete(
        "/webhooks/{id}",
        t.struct({"id": t.integer()}),
        t.boolean().optional(),
    )
    functions["getWebhookById"] = devto.get(
        "/webhooks/{id}",
        t.struct({"id": t.integer()}),
        t.proxy(renames["WebhookShow"]).optional(),
    )

    return Import(importer="devto", renames=renames, types=types, functions=functions)


with TypeGraph(name="devto") as g:
    devto = import_devto()

    public = policies.public()

    g.expose(getListings=devto.func("getListings").add_policy(public))
