package metatype:pyrt;

// use metatype:typegraph/runtimes;

interface shared {
  record req {
    op-name: string,
    in-json: string,
  }

  type res = result<string, string>;
}

interface typegate-wire {
  record req {
    op-name: string,
    in-json: string,
  }
  type res = result<string, string>;

  hostcall: func(req: req) -> res;
}

interface mat-wire {
  use shared.{req, res};

  record mat-info {
    op-name: string,
    mat-title: string,
    mat-hash: string,
    mat-data-json: string,
  }

  record init-args {
    metatype-version: string,
    expected-ops: list<mat-info>
  }

  record init-response {
    ok: bool
  }

  variant init-error {
    version-mismatch(string),
    unexpected-mat(mat-info),
    other(string)
  }

  init: func(args: init-args) -> result<init-response, init-error>;
  handle: func(req: req) -> res;
}

world pyrt {
  import typegate-wire;
  export mat-wire;
}
