from typegraph.runtimes.http import HTTPRuntime
from typegraph import policies, t
from typegraph.importers.base.importer import Import
from typegraph import TypeGraph
from typegraph.importers.google_discovery import GoogleDiscoveryImporter

GoogleDiscoveryImporter(
    "googleapi",
    url="https://mybusinessbusinessinformation.googleapis.com/$discovery/rest?version=v1",
).imp(False)


# Function generated by GoogleDiscoveryImporter. Do not change.
def import_googleapi():
    googleapi = HTTPRuntime("https://mybusinessbusinessinformation.googleapis.com/")

    renames = {
        "ErrorResponse": "_googleapi_1_ErrorResponse",
        "SearchChainsResponseIn": "_googleapi_2_SearchChainsResponseIn",
        "SearchChainsResponseOut": "_googleapi_3_SearchChainsResponseOut",
        "RepeatedEnumAttributeValueIn": "_googleapi_4_RepeatedEnumAttributeValueIn",
        "RepeatedEnumAttributeValueOut": "_googleapi_5_RepeatedEnumAttributeValueOut",
        "BatchGetCategoriesResponseIn": "_googleapi_6_BatchGetCategoriesResponseIn",
        "BatchGetCategoriesResponseOut": "_googleapi_7_BatchGetCategoriesResponseOut",
        "ProfileIn": "_googleapi_8_ProfileIn",
        "ProfileOut": "_googleapi_9_ProfileOut",
        "LocationIn": "_googleapi_10_LocationIn",
        "LocationOut": "_googleapi_11_LocationOut",
        "MoneyIn": "_googleapi_12_MoneyIn",
        "MoneyOut": "_googleapi_13_MoneyOut",
        "MoreHoursIn": "_googleapi_14_MoreHoursIn",
        "MoreHoursOut": "_googleapi_15_MoreHoursOut",
        "MetadataIn": "_googleapi_16_MetadataIn",
        "MetadataOut": "_googleapi_17_MetadataOut",
        "TimePeriodIn": "_googleapi_18_TimePeriodIn",
        "TimePeriodOut": "_googleapi_19_TimePeriodOut",
        "CategoryIn": "_googleapi_20_CategoryIn",
        "CategoryOut": "_googleapi_21_CategoryOut",
        "UriAttributeValueIn": "_googleapi_22_UriAttributeValueIn",
        "UriAttributeValueOut": "_googleapi_23_UriAttributeValueOut",
        "RelationshipDataIn": "_googleapi_24_RelationshipDataIn",
        "RelationshipDataOut": "_googleapi_25_RelationshipDataOut",
        "ServiceItemIn": "_googleapi_26_ServiceItemIn",
        "ServiceItemOut": "_googleapi_27_ServiceItemOut",
        "ServiceTypeIn": "_googleapi_28_ServiceTypeIn",
        "ServiceTypeOut": "_googleapi_29_ServiceTypeOut",
        "ListAttributeMetadataResponseIn": "_googleapi_30_ListAttributeMetadataResponseIn",
        "ListAttributeMetadataResponseOut": "_googleapi_31_ListAttributeMetadataResponseOut",
        "ChainIn": "_googleapi_32_ChainIn",
        "ChainOut": "_googleapi_33_ChainOut",
        "AttributesIn": "_googleapi_34_AttributesIn",
        "AttributesOut": "_googleapi_35_AttributesOut",
        "FreeFormServiceItemIn": "_googleapi_36_FreeFormServiceItemIn",
        "FreeFormServiceItemOut": "_googleapi_37_FreeFormServiceItemOut",
        "SpecialHourPeriodIn": "_googleapi_38_SpecialHourPeriodIn",
        "SpecialHourPeriodOut": "_googleapi_39_SpecialHourPeriodOut",
        "AssociateLocationRequestIn": "_googleapi_40_AssociateLocationRequestIn",
        "AssociateLocationRequestOut": "_googleapi_41_AssociateLocationRequestOut",
        "ServiceAreaBusinessIn": "_googleapi_42_ServiceAreaBusinessIn",
        "ServiceAreaBusinessOut": "_googleapi_43_ServiceAreaBusinessOut",
        "GoogleLocationIn": "_googleapi_44_GoogleLocationIn",
        "GoogleLocationOut": "_googleapi_45_GoogleLocationOut",
        "PlaceInfoIn": "_googleapi_46_PlaceInfoIn",
        "PlaceInfoOut": "_googleapi_47_PlaceInfoOut",
        "AttributeValueMetadataIn": "_googleapi_48_AttributeValueMetadataIn",
        "AttributeValueMetadataOut": "_googleapi_49_AttributeValueMetadataOut",
        "SpecialHoursIn": "_googleapi_50_SpecialHoursIn",
        "SpecialHoursOut": "_googleapi_51_SpecialHoursOut",
        "SearchGoogleLocationsRequestIn": "_googleapi_52_SearchGoogleLocationsRequestIn",
        "SearchGoogleLocationsRequestOut": "_googleapi_53_SearchGoogleLocationsRequestOut",
        "TimeOfDayIn": "_googleapi_54_TimeOfDayIn",
        "TimeOfDayOut": "_googleapi_55_TimeOfDayOut",
        "ClearLocationAssociationRequestIn": "_googleapi_56_ClearLocationAssociationRequestIn",
        "ClearLocationAssociationRequestOut": "_googleapi_57_ClearLocationAssociationRequestOut",
        "OpenInfoIn": "_googleapi_58_OpenInfoIn",
        "OpenInfoOut": "_googleapi_59_OpenInfoOut",
        "ListLocationsResponseIn": "_googleapi_60_ListLocationsResponseIn",
        "ListLocationsResponseOut": "_googleapi_61_ListLocationsResponseOut",
        "GoogleUpdatedLocationIn": "_googleapi_62_GoogleUpdatedLocationIn",
        "GoogleUpdatedLocationOut": "_googleapi_63_GoogleUpdatedLocationOut",
        "ListCategoriesResponseIn": "_googleapi_64_ListCategoriesResponseIn",
        "ListCategoriesResponseOut": "_googleapi_65_ListCategoriesResponseOut",
        "CategoriesIn": "_googleapi_66_CategoriesIn",
        "CategoriesOut": "_googleapi_67_CategoriesOut",
        "ChainNameIn": "_googleapi_68_ChainNameIn",
        "ChainNameOut": "_googleapi_69_ChainNameOut",
        "ChainUriIn": "_googleapi_70_ChainUriIn",
        "ChainUriOut": "_googleapi_71_ChainUriOut",
        "MoreHoursTypeIn": "_googleapi_72_MoreHoursTypeIn",
        "MoreHoursTypeOut": "_googleapi_73_MoreHoursTypeOut",
        "StructuredServiceItemIn": "_googleapi_74_StructuredServiceItemIn",
        "StructuredServiceItemOut": "_googleapi_75_StructuredServiceItemOut",
        "SearchGoogleLocationsResponseIn": "_googleapi_76_SearchGoogleLocationsResponseIn",
        "SearchGoogleLocationsResponseOut": "_googleapi_77_SearchGoogleLocationsResponseOut",
        "LatLngIn": "_googleapi_78_LatLngIn",
        "LatLngOut": "_googleapi_79_LatLngOut",
        "EmptyIn": "_googleapi_80_EmptyIn",
        "EmptyOut": "_googleapi_81_EmptyOut",
        "PostalAddressIn": "_googleapi_82_PostalAddressIn",
        "PostalAddressOut": "_googleapi_83_PostalAddressOut",
        "DateIn": "_googleapi_84_DateIn",
        "DateOut": "_googleapi_85_DateOut",
        "LabelIn": "_googleapi_86_LabelIn",
        "LabelOut": "_googleapi_87_LabelOut",
        "AttributeIn": "_googleapi_88_AttributeIn",
        "AttributeOut": "_googleapi_89_AttributeOut",
        "AdWordsLocationExtensionsIn": "_googleapi_90_AdWordsLocationExtensionsIn",
        "AdWordsLocationExtensionsOut": "_googleapi_91_AdWordsLocationExtensionsOut",
        "AttributeMetadataIn": "_googleapi_92_AttributeMetadataIn",
        "AttributeMetadataOut": "_googleapi_93_AttributeMetadataOut",
        "PhoneNumbersIn": "_googleapi_94_PhoneNumbersIn",
        "PhoneNumbersOut": "_googleapi_95_PhoneNumbersOut",
        "BusinessHoursIn": "_googleapi_96_BusinessHoursIn",
        "BusinessHoursOut": "_googleapi_97_BusinessHoursOut",
        "PlacesIn": "_googleapi_98_PlacesIn",
        "PlacesOut": "_googleapi_99_PlacesOut",
        "RelevantLocationIn": "_googleapi_100_RelevantLocationIn",
        "RelevantLocationOut": "_googleapi_101_RelevantLocationOut",
    }

    types = {}
    types["ErrorResponse"] = t.struct(
        {"code": t.integer(), "message": t.string(), "status": t.string()}
    ).named(renames["ErrorResponse"])
    types["SearchChainsResponseIn"] = t.struct(
        {"chains": t.array(t.proxy(renames["ChainIn"])).optional()}
    ).named(renames["SearchChainsResponseIn"])
    types["SearchChainsResponseOut"] = t.struct(
        {
            "chains": t.array(t.proxy(renames["ChainOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SearchChainsResponseOut"])
    types["RepeatedEnumAttributeValueIn"] = t.struct(
        {
            "unsetValues": t.array(t.string()).optional(),
            "setValues": t.array(t.string()).optional(),
        }
    ).named(renames["RepeatedEnumAttributeValueIn"])
    types["RepeatedEnumAttributeValueOut"] = t.struct(
        {
            "unsetValues": t.array(t.string()).optional(),
            "setValues": t.array(t.string()).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["RepeatedEnumAttributeValueOut"])
    types["BatchGetCategoriesResponseIn"] = t.struct(
        {"categories": t.array(t.proxy(renames["CategoryIn"])).optional()}
    ).named(renames["BatchGetCategoriesResponseIn"])
    types["BatchGetCategoriesResponseOut"] = t.struct(
        {
            "categories": t.array(t.proxy(renames["CategoryOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["BatchGetCategoriesResponseOut"])
    types["ProfileIn"] = t.struct({"description": t.string()}).named(
        renames["ProfileIn"]
    )
    types["ProfileOut"] = t.struct(
        {
            "description": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ProfileOut"])
    types["LocationIn"] = t.struct(
        {
            "storeCode": t.string().optional(),
            "latlng": t.proxy(renames["LatLngIn"]).optional(),
            "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
            "title": t.string(),
            "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
            "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
            "profile": t.proxy(renames["ProfileIn"]).optional(),
            "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
            "websiteUri": t.string().optional(),
            "categories": t.proxy(renames["CategoriesIn"]).optional(),
            "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
            "labels": t.array(t.string()).optional(),
            "languageCode": t.string().optional(),
            "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
            "adWordsLocationExtensions": t.proxy(
                renames["AdWordsLocationExtensionsIn"]
            ).optional(),
            "name": t.string().optional(),
            "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
            "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
            "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
        }
    ).named(renames["LocationIn"])
    types["LocationOut"] = t.struct(
        {
            "storeCode": t.string().optional(),
            "latlng": t.proxy(renames["LatLngOut"]).optional(),
            "phoneNumbers": t.proxy(renames["PhoneNumbersOut"]).optional(),
            "title": t.string(),
            "regularHours": t.proxy(renames["BusinessHoursOut"]).optional(),
            "storefrontAddress": t.proxy(renames["PostalAddressOut"]).optional(),
            "profile": t.proxy(renames["ProfileOut"]).optional(),
            "serviceItems": t.array(t.proxy(renames["ServiceItemOut"])).optional(),
            "websiteUri": t.string().optional(),
            "categories": t.proxy(renames["CategoriesOut"]).optional(),
            "serviceArea": t.proxy(renames["ServiceAreaBusinessOut"]).optional(),
            "labels": t.array(t.string()).optional(),
            "languageCode": t.string().optional(),
            "specialHours": t.proxy(renames["SpecialHoursOut"]).optional(),
            "adWordsLocationExtensions": t.proxy(
                renames["AdWordsLocationExtensionsOut"]
            ).optional(),
            "name": t.string().optional(),
            "moreHours": t.array(t.proxy(renames["MoreHoursOut"])).optional(),
            "metadata": t.proxy(renames["MetadataOut"]).optional(),
            "relationshipData": t.proxy(renames["RelationshipDataOut"]).optional(),
            "openInfo": t.proxy(renames["OpenInfoOut"]).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["LocationOut"])
    types["MoneyIn"] = t.struct(
        {
            "units": t.string().optional(),
            "currencyCode": t.string().optional(),
            "nanos": t.integer().optional(),
        }
    ).named(renames["MoneyIn"])
    types["MoneyOut"] = t.struct(
        {
            "units": t.string().optional(),
            "currencyCode": t.string().optional(),
            "nanos": t.integer().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["MoneyOut"])
    types["MoreHoursIn"] = t.struct(
        {
            "periods": t.array(t.proxy(renames["TimePeriodIn"])),
            "hoursTypeId": t.string(),
        }
    ).named(renames["MoreHoursIn"])
    types["MoreHoursOut"] = t.struct(
        {
            "periods": t.array(t.proxy(renames["TimePeriodOut"])),
            "hoursTypeId": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["MoreHoursOut"])
    types["MetadataIn"] = t.struct({"_": t.string().optional()}).named(
        renames["MetadataIn"]
    )
    types["MetadataOut"] = t.struct(
        {
            "mapsUri": t.string().optional(),
            "canOperateLocalPost": t.boolean().optional(),
            "canOperateHealthData": t.boolean().optional(),
            "hasVoiceOfMerchant": t.boolean().optional(),
            "canHaveBusinessCalls": t.boolean().optional(),
            "duplicateLocation": t.string().optional(),
            "newReviewUri": t.string().optional(),
            "canModifyServiceList": t.boolean().optional(),
            "hasPendingEdits": t.boolean().optional(),
            "hasGoogleUpdated": t.boolean().optional(),
            "placeId": t.string().optional(),
            "canOperateLodgingData": t.boolean().optional(),
            "canDelete": t.boolean().optional(),
            "canHaveFoodMenus": t.boolean().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["MetadataOut"])
    types["TimePeriodIn"] = t.struct(
        {
            "openTime": t.proxy(renames["TimeOfDayIn"]),
            "openDay": t.string(),
            "closeDay": t.string(),
            "closeTime": t.proxy(renames["TimeOfDayIn"]),
        }
    ).named(renames["TimePeriodIn"])
    types["TimePeriodOut"] = t.struct(
        {
            "openTime": t.proxy(renames["TimeOfDayOut"]),
            "openDay": t.string(),
            "closeDay": t.string(),
            "closeTime": t.proxy(renames["TimeOfDayOut"]),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["TimePeriodOut"])
    types["CategoryIn"] = t.struct({"name": t.string()}).named(renames["CategoryIn"])
    types["CategoryOut"] = t.struct(
        {
            "serviceTypes": t.array(t.proxy(renames["ServiceTypeOut"])).optional(),
            "displayName": t.string().optional(),
            "moreHoursTypes": t.array(t.proxy(renames["MoreHoursTypeOut"])).optional(),
            "name": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["CategoryOut"])
    types["UriAttributeValueIn"] = t.struct({"uri": t.string()}).named(
        renames["UriAttributeValueIn"]
    )
    types["UriAttributeValueOut"] = t.struct(
        {"uri": t.string(), "error": t.proxy(renames["ErrorResponse"]).optional()}
    ).named(renames["UriAttributeValueOut"])
    types["RelationshipDataIn"] = t.struct(
        {
            "parentLocation": t.proxy(renames["RelevantLocationIn"]).optional(),
            "childrenLocations": t.array(
                t.proxy(renames["RelevantLocationIn"])
            ).optional(),
            "parentChain": t.string().optional(),
        }
    ).named(renames["RelationshipDataIn"])
    types["RelationshipDataOut"] = t.struct(
        {
            "parentLocation": t.proxy(renames["RelevantLocationOut"]).optional(),
            "childrenLocations": t.array(
                t.proxy(renames["RelevantLocationOut"])
            ).optional(),
            "parentChain": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["RelationshipDataOut"])
    types["ServiceItemIn"] = t.struct(
        {
            "price": t.proxy(renames["MoneyIn"]).optional(),
            "freeFormServiceItem": t.proxy(renames["FreeFormServiceItemIn"]).optional(),
            "structuredServiceItem": t.proxy(
                renames["StructuredServiceItemIn"]
            ).optional(),
        }
    ).named(renames["ServiceItemIn"])
    types["ServiceItemOut"] = t.struct(
        {
            "price": t.proxy(renames["MoneyOut"]).optional(),
            "freeFormServiceItem": t.proxy(
                renames["FreeFormServiceItemOut"]
            ).optional(),
            "structuredServiceItem": t.proxy(
                renames["StructuredServiceItemOut"]
            ).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ServiceItemOut"])
    types["ServiceTypeIn"] = t.struct({"_": t.string().optional()}).named(
        renames["ServiceTypeIn"]
    )
    types["ServiceTypeOut"] = t.struct(
        {
            "serviceTypeId": t.string().optional(),
            "displayName": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ServiceTypeOut"])
    types["ListAttributeMetadataResponseIn"] = t.struct(
        {
            "nextPageToken": t.string().optional(),
            "attributeMetadata": t.array(
                t.proxy(renames["AttributeMetadataIn"])
            ).optional(),
        }
    ).named(renames["ListAttributeMetadataResponseIn"])
    types["ListAttributeMetadataResponseOut"] = t.struct(
        {
            "nextPageToken": t.string().optional(),
            "attributeMetadata": t.array(
                t.proxy(renames["AttributeMetadataOut"])
            ).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ListAttributeMetadataResponseOut"])
    types["ChainIn"] = t.struct(
        {
            "name": t.string(),
            "locationCount": t.integer().optional(),
            "websites": t.array(t.proxy(renames["ChainUriIn"])).optional(),
            "chainNames": t.array(t.proxy(renames["ChainNameIn"])).optional(),
        }
    ).named(renames["ChainIn"])
    types["ChainOut"] = t.struct(
        {
            "name": t.string(),
            "locationCount": t.integer().optional(),
            "websites": t.array(t.proxy(renames["ChainUriOut"])).optional(),
            "chainNames": t.array(t.proxy(renames["ChainNameOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ChainOut"])
    types["AttributesIn"] = t.struct(
        {
            "attributes": t.array(t.proxy(renames["AttributeIn"])).optional(),
            "name": t.string(),
        }
    ).named(renames["AttributesIn"])
    types["AttributesOut"] = t.struct(
        {
            "attributes": t.array(t.proxy(renames["AttributeOut"])).optional(),
            "name": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AttributesOut"])
    types["FreeFormServiceItemIn"] = t.struct(
        {"category": t.string(), "label": t.proxy(renames["LabelIn"])}
    ).named(renames["FreeFormServiceItemIn"])
    types["FreeFormServiceItemOut"] = t.struct(
        {
            "category": t.string(),
            "label": t.proxy(renames["LabelOut"]),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["FreeFormServiceItemOut"])
    types["SpecialHourPeriodIn"] = t.struct(
        {
            "openTime": t.proxy(renames["TimeOfDayIn"]).optional(),
            "endDate": t.proxy(renames["DateIn"]).optional(),
            "startDate": t.proxy(renames["DateIn"]),
            "closeTime": t.proxy(renames["TimeOfDayIn"]).optional(),
            "closed": t.boolean().optional(),
        }
    ).named(renames["SpecialHourPeriodIn"])
    types["SpecialHourPeriodOut"] = t.struct(
        {
            "openTime": t.proxy(renames["TimeOfDayOut"]).optional(),
            "endDate": t.proxy(renames["DateOut"]).optional(),
            "startDate": t.proxy(renames["DateOut"]),
            "closeTime": t.proxy(renames["TimeOfDayOut"]).optional(),
            "closed": t.boolean().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SpecialHourPeriodOut"])
    types["AssociateLocationRequestIn"] = t.struct(
        {"placeId": t.string().optional()}
    ).named(renames["AssociateLocationRequestIn"])
    types["AssociateLocationRequestOut"] = t.struct(
        {
            "placeId": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AssociateLocationRequestOut"])
    types["ServiceAreaBusinessIn"] = t.struct(
        {
            "regionCode": t.string().optional(),
            "places": t.proxy(renames["PlacesIn"]).optional(),
            "businessType": t.string(),
        }
    ).named(renames["ServiceAreaBusinessIn"])
    types["ServiceAreaBusinessOut"] = t.struct(
        {
            "regionCode": t.string().optional(),
            "places": t.proxy(renames["PlacesOut"]).optional(),
            "businessType": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ServiceAreaBusinessOut"])
    types["GoogleLocationIn"] = t.struct(
        {
            "name": t.string().optional(),
            "location": t.proxy(renames["LocationIn"]).optional(),
            "requestAdminRightsUri": t.string().optional(),
        }
    ).named(renames["GoogleLocationIn"])
    types["GoogleLocationOut"] = t.struct(
        {
            "name": t.string().optional(),
            "location": t.proxy(renames["LocationOut"]).optional(),
            "requestAdminRightsUri": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["GoogleLocationOut"])
    types["PlaceInfoIn"] = t.struct(
        {"placeName": t.string(), "placeId": t.string()}
    ).named(renames["PlaceInfoIn"])
    types["PlaceInfoOut"] = t.struct(
        {
            "placeName": t.string(),
            "placeId": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["PlaceInfoOut"])
    types["AttributeValueMetadataIn"] = t.struct(
        {
            "displayName": t.string().optional(),
            "value": t.struct({"_": t.string().optional()}).optional(),
        }
    ).named(renames["AttributeValueMetadataIn"])
    types["AttributeValueMetadataOut"] = t.struct(
        {
            "displayName": t.string().optional(),
            "value": t.struct({"_": t.string().optional()}).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AttributeValueMetadataOut"])
    types["SpecialHoursIn"] = t.struct(
        {"specialHourPeriods": t.array(t.proxy(renames["SpecialHourPeriodIn"]))}
    ).named(renames["SpecialHoursIn"])
    types["SpecialHoursOut"] = t.struct(
        {
            "specialHourPeriods": t.array(t.proxy(renames["SpecialHourPeriodOut"])),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SpecialHoursOut"])
    types["SearchGoogleLocationsRequestIn"] = t.struct(
        {
            "pageSize": t.integer().optional(),
            "location": t.proxy(renames["LocationIn"]).optional(),
            "query": t.string().optional(),
        }
    ).named(renames["SearchGoogleLocationsRequestIn"])
    types["SearchGoogleLocationsRequestOut"] = t.struct(
        {
            "pageSize": t.integer().optional(),
            "location": t.proxy(renames["LocationOut"]).optional(),
            "query": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SearchGoogleLocationsRequestOut"])
    types["TimeOfDayIn"] = t.struct(
        {
            "minutes": t.integer().optional(),
            "hours": t.integer().optional(),
            "seconds": t.integer().optional(),
            "nanos": t.integer().optional(),
        }
    ).named(renames["TimeOfDayIn"])
    types["TimeOfDayOut"] = t.struct(
        {
            "minutes": t.integer().optional(),
            "hours": t.integer().optional(),
            "seconds": t.integer().optional(),
            "nanos": t.integer().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["TimeOfDayOut"])
    types["ClearLocationAssociationRequestIn"] = t.struct(
        {"_": t.string().optional()}
    ).named(renames["ClearLocationAssociationRequestIn"])
    types["ClearLocationAssociationRequestOut"] = t.struct(
        {"error": t.proxy(renames["ErrorResponse"]).optional()}
    ).named(renames["ClearLocationAssociationRequestOut"])
    types["OpenInfoIn"] = t.struct(
        {"status": t.string(), "openingDate": t.proxy(renames["DateIn"]).optional()}
    ).named(renames["OpenInfoIn"])
    types["OpenInfoOut"] = t.struct(
        {
            "canReopen": t.boolean().optional(),
            "status": t.string(),
            "openingDate": t.proxy(renames["DateOut"]).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["OpenInfoOut"])
    types["ListLocationsResponseIn"] = t.struct(
        {
            "nextPageToken": t.string().optional(),
            "locations": t.array(t.proxy(renames["LocationIn"])).optional(),
            "totalSize": t.integer().optional(),
        }
    ).named(renames["ListLocationsResponseIn"])
    types["ListLocationsResponseOut"] = t.struct(
        {
            "nextPageToken": t.string().optional(),
            "locations": t.array(t.proxy(renames["LocationOut"])).optional(),
            "totalSize": t.integer().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ListLocationsResponseOut"])
    types["GoogleUpdatedLocationIn"] = t.struct(
        {
            "pendingMask": t.string().optional(),
            "diffMask": t.string().optional(),
            "location": t.proxy(renames["LocationIn"]).optional(),
        }
    ).named(renames["GoogleUpdatedLocationIn"])
    types["GoogleUpdatedLocationOut"] = t.struct(
        {
            "pendingMask": t.string().optional(),
            "diffMask": t.string().optional(),
            "location": t.proxy(renames["LocationOut"]).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["GoogleUpdatedLocationOut"])
    types["ListCategoriesResponseIn"] = t.struct(
        {
            "categories": t.array(t.proxy(renames["CategoryIn"])).optional(),
            "nextPageToken": t.string().optional(),
        }
    ).named(renames["ListCategoriesResponseIn"])
    types["ListCategoriesResponseOut"] = t.struct(
        {
            "categories": t.array(t.proxy(renames["CategoryOut"])).optional(),
            "nextPageToken": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ListCategoriesResponseOut"])
    types["CategoriesIn"] = t.struct(
        {
            "primaryCategory": t.proxy(renames["CategoryIn"]),
            "additionalCategories": t.array(t.proxy(renames["CategoryIn"])).optional(),
        }
    ).named(renames["CategoriesIn"])
    types["CategoriesOut"] = t.struct(
        {
            "primaryCategory": t.proxy(renames["CategoryOut"]),
            "additionalCategories": t.array(t.proxy(renames["CategoryOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["CategoriesOut"])
    types["ChainNameIn"] = t.struct(
        {"languageCode": t.string().optional(), "displayName": t.string().optional()}
    ).named(renames["ChainNameIn"])
    types["ChainNameOut"] = t.struct(
        {
            "languageCode": t.string().optional(),
            "displayName": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ChainNameOut"])
    types["ChainUriIn"] = t.struct({"uri": t.string().optional()}).named(
        renames["ChainUriIn"]
    )
    types["ChainUriOut"] = t.struct(
        {
            "uri": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ChainUriOut"])
    types["MoreHoursTypeIn"] = t.struct({"_": t.string().optional()}).named(
        renames["MoreHoursTypeIn"]
    )
    types["MoreHoursTypeOut"] = t.struct(
        {
            "hoursTypeId": t.string().optional(),
            "displayName": t.string().optional(),
            "localizedDisplayName": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["MoreHoursTypeOut"])
    types["StructuredServiceItemIn"] = t.struct(
        {"description": t.string().optional(), "serviceTypeId": t.string()}
    ).named(renames["StructuredServiceItemIn"])
    types["StructuredServiceItemOut"] = t.struct(
        {
            "description": t.string().optional(),
            "serviceTypeId": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["StructuredServiceItemOut"])
    types["SearchGoogleLocationsResponseIn"] = t.struct(
        {"googleLocations": t.array(t.proxy(renames["GoogleLocationIn"])).optional()}
    ).named(renames["SearchGoogleLocationsResponseIn"])
    types["SearchGoogleLocationsResponseOut"] = t.struct(
        {
            "googleLocations": t.array(
                t.proxy(renames["GoogleLocationOut"])
            ).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SearchGoogleLocationsResponseOut"])
    types["LatLngIn"] = t.struct(
        {"longitude": t.number().optional(), "latitude": t.number().optional()}
    ).named(renames["LatLngIn"])
    types["LatLngOut"] = t.struct(
        {
            "longitude": t.number().optional(),
            "latitude": t.number().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["LatLngOut"])
    types["EmptyIn"] = t.struct({"_": t.string().optional()}).named(renames["EmptyIn"])
    types["EmptyOut"] = t.struct(
        {"error": t.proxy(renames["ErrorResponse"]).optional()}
    ).named(renames["EmptyOut"])
    types["PostalAddressIn"] = t.struct(
        {
            "administrativeArea": t.string().optional(),
            "addressLines": t.array(t.string()).optional(),
            "locality": t.string().optional(),
            "postalCode": t.string().optional(),
            "regionCode": t.string(),
            "recipients": t.array(t.string()).optional(),
            "sublocality": t.string().optional(),
            "revision": t.integer().optional(),
            "sortingCode": t.string().optional(),
            "languageCode": t.string().optional(),
            "organization": t.string().optional(),
        }
    ).named(renames["PostalAddressIn"])
    types["PostalAddressOut"] = t.struct(
        {
            "administrativeArea": t.string().optional(),
            "addressLines": t.array(t.string()).optional(),
            "locality": t.string().optional(),
            "postalCode": t.string().optional(),
            "regionCode": t.string(),
            "recipients": t.array(t.string()).optional(),
            "sublocality": t.string().optional(),
            "revision": t.integer().optional(),
            "sortingCode": t.string().optional(),
            "languageCode": t.string().optional(),
            "organization": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["PostalAddressOut"])
    types["DateIn"] = t.struct(
        {
            "year": t.integer().optional(),
            "month": t.integer().optional(),
            "day": t.integer().optional(),
        }
    ).named(renames["DateIn"])
    types["DateOut"] = t.struct(
        {
            "year": t.integer().optional(),
            "month": t.integer().optional(),
            "day": t.integer().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["DateOut"])
    types["LabelIn"] = t.struct(
        {
            "languageCode": t.string().optional(),
            "displayName": t.string(),
            "description": t.string().optional(),
        }
    ).named(renames["LabelIn"])
    types["LabelOut"] = t.struct(
        {
            "languageCode": t.string().optional(),
            "displayName": t.string(),
            "description": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["LabelOut"])
    types["AttributeIn"] = t.struct(
        {
            "uriValues": t.array(t.proxy(renames["UriAttributeValueIn"])).optional(),
            "values": t.array(t.struct({"_": t.string().optional()})).optional(),
            "repeatedEnumValue": t.proxy(
                renames["RepeatedEnumAttributeValueIn"]
            ).optional(),
            "name": t.string(),
        }
    ).named(renames["AttributeIn"])
    types["AttributeOut"] = t.struct(
        {
            "uriValues": t.array(t.proxy(renames["UriAttributeValueOut"])).optional(),
            "values": t.array(t.struct({"_": t.string().optional()})).optional(),
            "valueType": t.string().optional(),
            "repeatedEnumValue": t.proxy(
                renames["RepeatedEnumAttributeValueOut"]
            ).optional(),
            "name": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AttributeOut"])
    types["AdWordsLocationExtensionsIn"] = t.struct({"adPhone": t.string()}).named(
        renames["AdWordsLocationExtensionsIn"]
    )
    types["AdWordsLocationExtensionsOut"] = t.struct(
        {"adPhone": t.string(), "error": t.proxy(renames["ErrorResponse"]).optional()}
    ).named(renames["AdWordsLocationExtensionsOut"])
    types["AttributeMetadataIn"] = t.struct(
        {
            "deprecated": t.boolean().optional(),
            "groupDisplayName": t.string().optional(),
            "valueType": t.string().optional(),
            "repeatable": t.boolean().optional(),
            "displayName": t.string().optional(),
            "parent": t.string().optional(),
            "valueMetadata": t.array(
                t.proxy(renames["AttributeValueMetadataIn"])
            ).optional(),
        }
    ).named(renames["AttributeMetadataIn"])
    types["AttributeMetadataOut"] = t.struct(
        {
            "deprecated": t.boolean().optional(),
            "groupDisplayName": t.string().optional(),
            "valueType": t.string().optional(),
            "repeatable": t.boolean().optional(),
            "displayName": t.string().optional(),
            "parent": t.string().optional(),
            "valueMetadata": t.array(
                t.proxy(renames["AttributeValueMetadataOut"])
            ).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AttributeMetadataOut"])
    types["PhoneNumbersIn"] = t.struct(
        {"additionalPhones": t.array(t.string()).optional(), "primaryPhone": t.string()}
    ).named(renames["PhoneNumbersIn"])
    types["PhoneNumbersOut"] = t.struct(
        {
            "additionalPhones": t.array(t.string()).optional(),
            "primaryPhone": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["PhoneNumbersOut"])
    types["BusinessHoursIn"] = t.struct(
        {"periods": t.array(t.proxy(renames["TimePeriodIn"]))}
    ).named(renames["BusinessHoursIn"])
    types["BusinessHoursOut"] = t.struct(
        {
            "periods": t.array(t.proxy(renames["TimePeriodOut"])),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["BusinessHoursOut"])
    types["PlacesIn"] = t.struct(
        {"placeInfos": t.array(t.proxy(renames["PlaceInfoIn"])).optional()}
    ).named(renames["PlacesIn"])
    types["PlacesOut"] = t.struct(
        {
            "placeInfos": t.array(t.proxy(renames["PlaceInfoOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["PlacesOut"])
    types["RelevantLocationIn"] = t.struct(
        {"relationType": t.string(), "placeId": t.string()}
    ).named(renames["RelevantLocationIn"])
    types["RelevantLocationOut"] = t.struct(
        {
            "relationType": t.string(),
            "placeId": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["RelevantLocationOut"])

    functions = {}
    functions["locationsUpdateAttributes"] = googleapi.patch(
        "v1/{name}",
        t.struct(
            {
                "name": t.string().optional(),
                "updateMask": t.string(),
                "validateOnly": t.boolean().optional(),
                "storeCode": t.string().optional(),
                "latlng": t.proxy(renames["LatLngIn"]).optional(),
                "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
                "title": t.string(),
                "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
                "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
                "profile": t.proxy(renames["ProfileIn"]).optional(),
                "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
                "websiteUri": t.string().optional(),
                "categories": t.proxy(renames["CategoriesIn"]).optional(),
                "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
                "labels": t.array(t.string()).optional(),
                "languageCode": t.string().optional(),
                "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
                "adWordsLocationExtensions": t.proxy(
                    renames["AdWordsLocationExtensionsIn"]
                ).optional(),
                "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
                "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
                "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsClearLocationAssociation"] = googleapi.patch(
        "v1/{name}",
        t.struct(
            {
                "name": t.string().optional(),
                "updateMask": t.string(),
                "validateOnly": t.boolean().optional(),
                "storeCode": t.string().optional(),
                "latlng": t.proxy(renames["LatLngIn"]).optional(),
                "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
                "title": t.string(),
                "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
                "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
                "profile": t.proxy(renames["ProfileIn"]).optional(),
                "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
                "websiteUri": t.string().optional(),
                "categories": t.proxy(renames["CategoriesIn"]).optional(),
                "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
                "labels": t.array(t.string()).optional(),
                "languageCode": t.string().optional(),
                "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
                "adWordsLocationExtensions": t.proxy(
                    renames["AdWordsLocationExtensionsIn"]
                ).optional(),
                "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
                "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
                "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsGetAttributes"] = googleapi.patch(
        "v1/{name}",
        t.struct(
            {
                "name": t.string().optional(),
                "updateMask": t.string(),
                "validateOnly": t.boolean().optional(),
                "storeCode": t.string().optional(),
                "latlng": t.proxy(renames["LatLngIn"]).optional(),
                "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
                "title": t.string(),
                "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
                "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
                "profile": t.proxy(renames["ProfileIn"]).optional(),
                "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
                "websiteUri": t.string().optional(),
                "categories": t.proxy(renames["CategoriesIn"]).optional(),
                "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
                "labels": t.array(t.string()).optional(),
                "languageCode": t.string().optional(),
                "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
                "adWordsLocationExtensions": t.proxy(
                    renames["AdWordsLocationExtensionsIn"]
                ).optional(),
                "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
                "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
                "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsGet"] = googleapi.patch(
        "v1/{name}",
        t.struct(
            {
                "name": t.string().optional(),
                "updateMask": t.string(),
                "validateOnly": t.boolean().optional(),
                "storeCode": t.string().optional(),
                "latlng": t.proxy(renames["LatLngIn"]).optional(),
                "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
                "title": t.string(),
                "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
                "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
                "profile": t.proxy(renames["ProfileIn"]).optional(),
                "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
                "websiteUri": t.string().optional(),
                "categories": t.proxy(renames["CategoriesIn"]).optional(),
                "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
                "labels": t.array(t.string()).optional(),
                "languageCode": t.string().optional(),
                "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
                "adWordsLocationExtensions": t.proxy(
                    renames["AdWordsLocationExtensionsIn"]
                ).optional(),
                "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
                "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
                "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsGetGoogleUpdated"] = googleapi.patch(
        "v1/{name}",
        t.struct(
            {
                "name": t.string().optional(),
                "updateMask": t.string(),
                "validateOnly": t.boolean().optional(),
                "storeCode": t.string().optional(),
                "latlng": t.proxy(renames["LatLngIn"]).optional(),
                "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
                "title": t.string(),
                "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
                "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
                "profile": t.proxy(renames["ProfileIn"]).optional(),
                "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
                "websiteUri": t.string().optional(),
                "categories": t.proxy(renames["CategoriesIn"]).optional(),
                "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
                "labels": t.array(t.string()).optional(),
                "languageCode": t.string().optional(),
                "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
                "adWordsLocationExtensions": t.proxy(
                    renames["AdWordsLocationExtensionsIn"]
                ).optional(),
                "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
                "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
                "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsAssociate"] = googleapi.patch(
        "v1/{name}",
        t.struct(
            {
                "name": t.string().optional(),
                "updateMask": t.string(),
                "validateOnly": t.boolean().optional(),
                "storeCode": t.string().optional(),
                "latlng": t.proxy(renames["LatLngIn"]).optional(),
                "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
                "title": t.string(),
                "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
                "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
                "profile": t.proxy(renames["ProfileIn"]).optional(),
                "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
                "websiteUri": t.string().optional(),
                "categories": t.proxy(renames["CategoriesIn"]).optional(),
                "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
                "labels": t.array(t.string()).optional(),
                "languageCode": t.string().optional(),
                "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
                "adWordsLocationExtensions": t.proxy(
                    renames["AdWordsLocationExtensionsIn"]
                ).optional(),
                "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
                "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
                "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsDelete"] = googleapi.patch(
        "v1/{name}",
        t.struct(
            {
                "name": t.string().optional(),
                "updateMask": t.string(),
                "validateOnly": t.boolean().optional(),
                "storeCode": t.string().optional(),
                "latlng": t.proxy(renames["LatLngIn"]).optional(),
                "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
                "title": t.string(),
                "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
                "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
                "profile": t.proxy(renames["ProfileIn"]).optional(),
                "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
                "websiteUri": t.string().optional(),
                "categories": t.proxy(renames["CategoriesIn"]).optional(),
                "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
                "labels": t.array(t.string()).optional(),
                "languageCode": t.string().optional(),
                "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
                "adWordsLocationExtensions": t.proxy(
                    renames["AdWordsLocationExtensionsIn"]
                ).optional(),
                "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
                "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
                "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsPatch"] = googleapi.patch(
        "v1/{name}",
        t.struct(
            {
                "name": t.string().optional(),
                "updateMask": t.string(),
                "validateOnly": t.boolean().optional(),
                "storeCode": t.string().optional(),
                "latlng": t.proxy(renames["LatLngIn"]).optional(),
                "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
                "title": t.string(),
                "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
                "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
                "profile": t.proxy(renames["ProfileIn"]).optional(),
                "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
                "websiteUri": t.string().optional(),
                "categories": t.proxy(renames["CategoriesIn"]).optional(),
                "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
                "labels": t.array(t.string()).optional(),
                "languageCode": t.string().optional(),
                "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
                "adWordsLocationExtensions": t.proxy(
                    renames["AdWordsLocationExtensionsIn"]
                ).optional(),
                "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
                "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
                "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsAttributesGetGoogleUpdated"] = googleapi.get(
        "v1/{name}:getGoogleUpdated",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["AttributesOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["accountsLocationsCreate"] = googleapi.get(
        "v1/{parent}/locations",
        t.struct(
            {
                "pageToken": t.string().optional(),
                "parent": t.string(),
                "filter": t.string().optional(),
                "pageSize": t.integer().optional(),
                "orderBy": t.string().optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["ListLocationsResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["accountsLocationsList"] = googleapi.get(
        "v1/{parent}/locations",
        t.struct(
            {
                "pageToken": t.string().optional(),
                "parent": t.string(),
                "filter": t.string().optional(),
                "pageSize": t.integer().optional(),
                "orderBy": t.string().optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["ListLocationsResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["attributesList"] = googleapi.get(
        "v1/attributes",
        t.struct(
            {
                "regionCode": t.string().optional(),
                "categoryName": t.string().optional(),
                "pageToken": t.string().optional(),
                "languageCode": t.string().optional(),
                "showAll": t.boolean().optional(),
                "pageSize": t.integer().optional(),
                "parent": t.string().optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["ListAttributeMetadataResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["googleLocationsSearch"] = googleapi.post(
        "v1/googleLocations:search",
        t.struct(
            {
                "pageSize": t.integer().optional(),
                "location": t.proxy(renames["LocationIn"]).optional(),
                "query": t.string().optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["SearchGoogleLocationsResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["categoriesBatchGet"] = googleapi.get(
        "v1/categories",
        t.struct(
            {
                "filter": t.string().optional(),
                "pageToken": t.string().optional(),
                "languageCode": t.string(),
                "regionCode": t.string(),
                "pageSize": t.integer().optional(),
                "view": t.string(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["ListCategoriesResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["categoriesList"] = googleapi.get(
        "v1/categories",
        t.struct(
            {
                "filter": t.string().optional(),
                "pageToken": t.string().optional(),
                "languageCode": t.string(),
                "regionCode": t.string(),
                "pageSize": t.integer().optional(),
                "view": t.string(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["ListCategoriesResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["chainsSearch"] = googleapi.get(
        "v1/{name}",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["ChainOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["chainsGet"] = googleapi.get(
        "v1/{name}",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["ChainOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )

    return Import(
        importer="googleapi", renames=renames, types=types, functions=functions
    )


with TypeGraph(name="mybusinessbusinessinformation") as g:
    googleapi = import_googleapi()
    public = policies.public()
    g.expose(**{name: f.add_policy(public) for name, f in googleapi.functions.items()})
