from box import Box
from typegraph.runtimes.http import HTTPRuntime
from typegraph import policies, t
from typegraph.importers.base.importer import Import
from typegraph import TypeGraph
from typegraph.importers.google_discovery import GoogleDiscoveryImporter

GoogleDiscoveryImporter(
    "mybusiness",
    url="https://mybusinessbusinessinformation.googleapis.com/$discovery/rest?version=v1",
).imp(False)


# Function generated by GoogleDiscoveryImporter. Do not change.
def import_googleapi():
    googleapi = HTTPRuntime("https://mybusinessbusinessinformation.googleapis.com/")

    renames = {
        "ErrorResponse": "_googleapi_1_ErrorResponse",
        "StructuredServiceItemIn": "_googleapi_2_StructuredServiceItemIn",
        "StructuredServiceItemOut": "_googleapi_3_StructuredServiceItemOut",
        "LabelIn": "_googleapi_4_LabelIn",
        "LabelOut": "_googleapi_5_LabelOut",
        "PhoneNumbersIn": "_googleapi_6_PhoneNumbersIn",
        "PhoneNumbersOut": "_googleapi_7_PhoneNumbersOut",
        "MoreHoursIn": "_googleapi_8_MoreHoursIn",
        "MoreHoursOut": "_googleapi_9_MoreHoursOut",
        "PlaceInfoIn": "_googleapi_10_PlaceInfoIn",
        "PlaceInfoOut": "_googleapi_11_PlaceInfoOut",
        "CategoriesIn": "_googleapi_12_CategoriesIn",
        "CategoriesOut": "_googleapi_13_CategoriesOut",
        "ServiceItemIn": "_googleapi_14_ServiceItemIn",
        "ServiceItemOut": "_googleapi_15_ServiceItemOut",
        "SpecialHoursIn": "_googleapi_16_SpecialHoursIn",
        "SpecialHoursOut": "_googleapi_17_SpecialHoursOut",
        "SearchGoogleLocationsRequestIn": "_googleapi_18_SearchGoogleLocationsRequestIn",
        "SearchGoogleLocationsRequestOut": "_googleapi_19_SearchGoogleLocationsRequestOut",
        "EmptyIn": "_googleapi_20_EmptyIn",
        "EmptyOut": "_googleapi_21_EmptyOut",
        "OpenInfoIn": "_googleapi_22_OpenInfoIn",
        "OpenInfoOut": "_googleapi_23_OpenInfoOut",
        "AttributeIn": "_googleapi_24_AttributeIn",
        "AttributeOut": "_googleapi_25_AttributeOut",
        "MetadataIn": "_googleapi_26_MetadataIn",
        "MetadataOut": "_googleapi_27_MetadataOut",
        "UriAttributeValueIn": "_googleapi_28_UriAttributeValueIn",
        "UriAttributeValueOut": "_googleapi_29_UriAttributeValueOut",
        "RepeatedEnumAttributeValueIn": "_googleapi_30_RepeatedEnumAttributeValueIn",
        "RepeatedEnumAttributeValueOut": "_googleapi_31_RepeatedEnumAttributeValueOut",
        "PostalAddressIn": "_googleapi_32_PostalAddressIn",
        "PostalAddressOut": "_googleapi_33_PostalAddressOut",
        "CategoryIn": "_googleapi_34_CategoryIn",
        "CategoryOut": "_googleapi_35_CategoryOut",
        "ChainNameIn": "_googleapi_36_ChainNameIn",
        "ChainNameOut": "_googleapi_37_ChainNameOut",
        "AssociateLocationRequestIn": "_googleapi_38_AssociateLocationRequestIn",
        "AssociateLocationRequestOut": "_googleapi_39_AssociateLocationRequestOut",
        "LatLngIn": "_googleapi_40_LatLngIn",
        "LatLngOut": "_googleapi_41_LatLngOut",
        "AttributeValueMetadataIn": "_googleapi_42_AttributeValueMetadataIn",
        "AttributeValueMetadataOut": "_googleapi_43_AttributeValueMetadataOut",
        "MoneyIn": "_googleapi_44_MoneyIn",
        "MoneyOut": "_googleapi_45_MoneyOut",
        "ServiceAreaBusinessIn": "_googleapi_46_ServiceAreaBusinessIn",
        "ServiceAreaBusinessOut": "_googleapi_47_ServiceAreaBusinessOut",
        "MoreHoursTypeIn": "_googleapi_48_MoreHoursTypeIn",
        "MoreHoursTypeOut": "_googleapi_49_MoreHoursTypeOut",
        "TimePeriodIn": "_googleapi_50_TimePeriodIn",
        "TimePeriodOut": "_googleapi_51_TimePeriodOut",
        "ProfileIn": "_googleapi_52_ProfileIn",
        "ProfileOut": "_googleapi_53_ProfileOut",
        "GoogleUpdatedLocationIn": "_googleapi_54_GoogleUpdatedLocationIn",
        "GoogleUpdatedLocationOut": "_googleapi_55_GoogleUpdatedLocationOut",
        "TimeOfDayIn": "_googleapi_56_TimeOfDayIn",
        "TimeOfDayOut": "_googleapi_57_TimeOfDayOut",
        "ClearLocationAssociationRequestIn": "_googleapi_58_ClearLocationAssociationRequestIn",
        "ClearLocationAssociationRequestOut": "_googleapi_59_ClearLocationAssociationRequestOut",
        "LocationIn": "_googleapi_60_LocationIn",
        "LocationOut": "_googleapi_61_LocationOut",
        "ListCategoriesResponseIn": "_googleapi_62_ListCategoriesResponseIn",
        "ListCategoriesResponseOut": "_googleapi_63_ListCategoriesResponseOut",
        "ServiceTypeIn": "_googleapi_64_ServiceTypeIn",
        "ServiceTypeOut": "_googleapi_65_ServiceTypeOut",
        "GoogleLocationIn": "_googleapi_66_GoogleLocationIn",
        "GoogleLocationOut": "_googleapi_67_GoogleLocationOut",
        "AdWordsLocationExtensionsIn": "_googleapi_68_AdWordsLocationExtensionsIn",
        "AdWordsLocationExtensionsOut": "_googleapi_69_AdWordsLocationExtensionsOut",
        "AttributeMetadataIn": "_googleapi_70_AttributeMetadataIn",
        "AttributeMetadataOut": "_googleapi_71_AttributeMetadataOut",
        "ChainUriIn": "_googleapi_72_ChainUriIn",
        "ChainUriOut": "_googleapi_73_ChainUriOut",
        "RelationshipDataIn": "_googleapi_74_RelationshipDataIn",
        "RelationshipDataOut": "_googleapi_75_RelationshipDataOut",
        "ChainIn": "_googleapi_76_ChainIn",
        "ChainOut": "_googleapi_77_ChainOut",
        "FreeFormServiceItemIn": "_googleapi_78_FreeFormServiceItemIn",
        "FreeFormServiceItemOut": "_googleapi_79_FreeFormServiceItemOut",
        "SpecialHourPeriodIn": "_googleapi_80_SpecialHourPeriodIn",
        "SpecialHourPeriodOut": "_googleapi_81_SpecialHourPeriodOut",
        "SearchChainsResponseIn": "_googleapi_82_SearchChainsResponseIn",
        "SearchChainsResponseOut": "_googleapi_83_SearchChainsResponseOut",
        "BusinessHoursIn": "_googleapi_84_BusinessHoursIn",
        "BusinessHoursOut": "_googleapi_85_BusinessHoursOut",
        "AttributesIn": "_googleapi_86_AttributesIn",
        "AttributesOut": "_googleapi_87_AttributesOut",
        "ListAttributeMetadataResponseIn": "_googleapi_88_ListAttributeMetadataResponseIn",
        "ListAttributeMetadataResponseOut": "_googleapi_89_ListAttributeMetadataResponseOut",
        "PlacesIn": "_googleapi_90_PlacesIn",
        "PlacesOut": "_googleapi_91_PlacesOut",
        "BatchGetCategoriesResponseIn": "_googleapi_92_BatchGetCategoriesResponseIn",
        "BatchGetCategoriesResponseOut": "_googleapi_93_BatchGetCategoriesResponseOut",
        "DateIn": "_googleapi_94_DateIn",
        "DateOut": "_googleapi_95_DateOut",
        "SearchGoogleLocationsResponseIn": "_googleapi_96_SearchGoogleLocationsResponseIn",
        "SearchGoogleLocationsResponseOut": "_googleapi_97_SearchGoogleLocationsResponseOut",
        "RelevantLocationIn": "_googleapi_98_RelevantLocationIn",
        "RelevantLocationOut": "_googleapi_99_RelevantLocationOut",
        "ListLocationsResponseIn": "_googleapi_100_ListLocationsResponseIn",
        "ListLocationsResponseOut": "_googleapi_101_ListLocationsResponseOut",
    }

    types = {}
    types["ErrorResponse"] = t.struct(
        {"code": t.integer(), "message": t.string(), "status": t.string()}
    ).named(renames["ErrorResponse"])
    types["StructuredServiceItemIn"] = t.struct(
        {"serviceTypeId": t.string(), "description": t.string().optional()}
    ).named(renames["StructuredServiceItemIn"])
    types["StructuredServiceItemOut"] = t.struct(
        {
            "serviceTypeId": t.string(),
            "description": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["StructuredServiceItemOut"])
    types["LabelIn"] = t.struct(
        {
            "displayName": t.string(),
            "description": t.string().optional(),
            "languageCode": t.string().optional(),
        }
    ).named(renames["LabelIn"])
    types["LabelOut"] = t.struct(
        {
            "displayName": t.string(),
            "description": t.string().optional(),
            "languageCode": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["LabelOut"])
    types["PhoneNumbersIn"] = t.struct(
        {"additionalPhones": t.array(t.string()).optional(), "primaryPhone": t.string()}
    ).named(renames["PhoneNumbersIn"])
    types["PhoneNumbersOut"] = t.struct(
        {
            "additionalPhones": t.array(t.string()).optional(),
            "primaryPhone": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["PhoneNumbersOut"])
    types["MoreHoursIn"] = t.struct(
        {
            "periods": t.array(t.proxy(renames["TimePeriodIn"])),
            "hoursTypeId": t.string(),
        }
    ).named(renames["MoreHoursIn"])
    types["MoreHoursOut"] = t.struct(
        {
            "periods": t.array(t.proxy(renames["TimePeriodOut"])),
            "hoursTypeId": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["MoreHoursOut"])
    types["PlaceInfoIn"] = t.struct(
        {"placeId": t.string(), "placeName": t.string()}
    ).named(renames["PlaceInfoIn"])
    types["PlaceInfoOut"] = t.struct(
        {
            "placeId": t.string(),
            "placeName": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["PlaceInfoOut"])
    types["CategoriesIn"] = t.struct(
        {
            "primaryCategory": t.proxy(renames["CategoryIn"]),
            "additionalCategories": t.array(t.proxy(renames["CategoryIn"])).optional(),
        }
    ).named(renames["CategoriesIn"])
    types["CategoriesOut"] = t.struct(
        {
            "primaryCategory": t.proxy(renames["CategoryOut"]),
            "additionalCategories": t.array(t.proxy(renames["CategoryOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["CategoriesOut"])
    types["ServiceItemIn"] = t.struct(
        {
            "price": t.proxy(renames["MoneyIn"]).optional(),
            "freeFormServiceItem": t.proxy(renames["FreeFormServiceItemIn"]).optional(),
            "structuredServiceItem": t.proxy(
                renames["StructuredServiceItemIn"]
            ).optional(),
        }
    ).named(renames["ServiceItemIn"])
    types["ServiceItemOut"] = t.struct(
        {
            "price": t.proxy(renames["MoneyOut"]).optional(),
            "freeFormServiceItem": t.proxy(
                renames["FreeFormServiceItemOut"]
            ).optional(),
            "structuredServiceItem": t.proxy(
                renames["StructuredServiceItemOut"]
            ).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ServiceItemOut"])
    types["SpecialHoursIn"] = t.struct(
        {"specialHourPeriods": t.array(t.proxy(renames["SpecialHourPeriodIn"]))}
    ).named(renames["SpecialHoursIn"])
    types["SpecialHoursOut"] = t.struct(
        {
            "specialHourPeriods": t.array(t.proxy(renames["SpecialHourPeriodOut"])),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SpecialHoursOut"])
    types["SearchGoogleLocationsRequestIn"] = t.struct(
        {
            "location": t.proxy(renames["LocationIn"]).optional(),
            "pageSize": t.integer().optional(),
            "query": t.string().optional(),
        }
    ).named(renames["SearchGoogleLocationsRequestIn"])
    types["SearchGoogleLocationsRequestOut"] = t.struct(
        {
            "location": t.proxy(renames["LocationOut"]).optional(),
            "pageSize": t.integer().optional(),
            "query": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SearchGoogleLocationsRequestOut"])
    types["EmptyIn"] = t.struct({"_": t.string().optional()}).named(renames["EmptyIn"])
    types["EmptyOut"] = t.struct(
        {"error": t.proxy(renames["ErrorResponse"]).optional()}
    ).named(renames["EmptyOut"])
    types["OpenInfoIn"] = t.struct(
        {"status": t.string(), "openingDate": t.proxy(renames["DateIn"]).optional()}
    ).named(renames["OpenInfoIn"])
    types["OpenInfoOut"] = t.struct(
        {
            "status": t.string(),
            "canReopen": t.boolean().optional(),
            "openingDate": t.proxy(renames["DateOut"]).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["OpenInfoOut"])
    types["AttributeIn"] = t.struct(
        {
            "repeatedEnumValue": t.proxy(
                renames["RepeatedEnumAttributeValueIn"]
            ).optional(),
            "name": t.string(),
            "values": t.array(t.struct({"_": t.string().optional()})).optional(),
            "uriValues": t.array(t.proxy(renames["UriAttributeValueIn"])).optional(),
        }
    ).named(renames["AttributeIn"])
    types["AttributeOut"] = t.struct(
        {
            "valueType": t.string().optional(),
            "repeatedEnumValue": t.proxy(
                renames["RepeatedEnumAttributeValueOut"]
            ).optional(),
            "name": t.string(),
            "values": t.array(t.struct({"_": t.string().optional()})).optional(),
            "uriValues": t.array(t.proxy(renames["UriAttributeValueOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AttributeOut"])
    types["MetadataIn"] = t.struct({"_": t.string().optional()}).named(
        renames["MetadataIn"]
    )
    types["MetadataOut"] = t.struct(
        {
            "placeId": t.string().optional(),
            "duplicateLocation": t.string().optional(),
            "canModifyServiceList": t.boolean().optional(),
            "canDelete": t.boolean().optional(),
            "newReviewUri": t.string().optional(),
            "canOperateHealthData": t.boolean().optional(),
            "canHaveFoodMenus": t.boolean().optional(),
            "hasGoogleUpdated": t.boolean().optional(),
            "canHaveBusinessCalls": t.boolean().optional(),
            "canOperateLodgingData": t.boolean().optional(),
            "mapsUri": t.string().optional(),
            "hasPendingEdits": t.boolean().optional(),
            "canOperateLocalPost": t.boolean().optional(),
            "hasVoiceOfMerchant": t.boolean().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["MetadataOut"])
    types["UriAttributeValueIn"] = t.struct({"uri": t.string()}).named(
        renames["UriAttributeValueIn"]
    )
    types["UriAttributeValueOut"] = t.struct(
        {"uri": t.string(), "error": t.proxy(renames["ErrorResponse"]).optional()}
    ).named(renames["UriAttributeValueOut"])
    types["RepeatedEnumAttributeValueIn"] = t.struct(
        {
            "setValues": t.array(t.string()).optional(),
            "unsetValues": t.array(t.string()).optional(),
        }
    ).named(renames["RepeatedEnumAttributeValueIn"])
    types["RepeatedEnumAttributeValueOut"] = t.struct(
        {
            "setValues": t.array(t.string()).optional(),
            "unsetValues": t.array(t.string()).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["RepeatedEnumAttributeValueOut"])
    types["PostalAddressIn"] = t.struct(
        {
            "organization": t.string().optional(),
            "locality": t.string().optional(),
            "sublocality": t.string().optional(),
            "regionCode": t.string(),
            "recipients": t.array(t.string()).optional(),
            "administrativeArea": t.string().optional(),
            "languageCode": t.string().optional(),
            "sortingCode": t.string().optional(),
            "postalCode": t.string().optional(),
            "addressLines": t.array(t.string()).optional(),
            "revision": t.integer().optional(),
        }
    ).named(renames["PostalAddressIn"])
    types["PostalAddressOut"] = t.struct(
        {
            "organization": t.string().optional(),
            "locality": t.string().optional(),
            "sublocality": t.string().optional(),
            "regionCode": t.string(),
            "recipients": t.array(t.string()).optional(),
            "administrativeArea": t.string().optional(),
            "languageCode": t.string().optional(),
            "sortingCode": t.string().optional(),
            "postalCode": t.string().optional(),
            "addressLines": t.array(t.string()).optional(),
            "revision": t.integer().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["PostalAddressOut"])
    types["CategoryIn"] = t.struct({"name": t.string()}).named(renames["CategoryIn"])
    types["CategoryOut"] = t.struct(
        {
            "moreHoursTypes": t.array(t.proxy(renames["MoreHoursTypeOut"])).optional(),
            "name": t.string(),
            "displayName": t.string().optional(),
            "serviceTypes": t.array(t.proxy(renames["ServiceTypeOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["CategoryOut"])
    types["ChainNameIn"] = t.struct(
        {"languageCode": t.string().optional(), "displayName": t.string().optional()}
    ).named(renames["ChainNameIn"])
    types["ChainNameOut"] = t.struct(
        {
            "languageCode": t.string().optional(),
            "displayName": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ChainNameOut"])
    types["AssociateLocationRequestIn"] = t.struct(
        {"placeId": t.string().optional()}
    ).named(renames["AssociateLocationRequestIn"])
    types["AssociateLocationRequestOut"] = t.struct(
        {
            "placeId": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AssociateLocationRequestOut"])
    types["LatLngIn"] = t.struct(
        {"longitude": t.number().optional(), "latitude": t.number().optional()}
    ).named(renames["LatLngIn"])
    types["LatLngOut"] = t.struct(
        {
            "longitude": t.number().optional(),
            "latitude": t.number().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["LatLngOut"])
    types["AttributeValueMetadataIn"] = t.struct(
        {
            "value": t.struct({"_": t.string().optional()}).optional(),
            "displayName": t.string().optional(),
        }
    ).named(renames["AttributeValueMetadataIn"])
    types["AttributeValueMetadataOut"] = t.struct(
        {
            "value": t.struct({"_": t.string().optional()}).optional(),
            "displayName": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AttributeValueMetadataOut"])
    types["MoneyIn"] = t.struct(
        {
            "nanos": t.integer().optional(),
            "currencyCode": t.string().optional(),
            "units": t.string().optional(),
        }
    ).named(renames["MoneyIn"])
    types["MoneyOut"] = t.struct(
        {
            "nanos": t.integer().optional(),
            "currencyCode": t.string().optional(),
            "units": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["MoneyOut"])
    types["ServiceAreaBusinessIn"] = t.struct(
        {
            "businessType": t.string(),
            "regionCode": t.string().optional(),
            "places": t.proxy(renames["PlacesIn"]).optional(),
        }
    ).named(renames["ServiceAreaBusinessIn"])
    types["ServiceAreaBusinessOut"] = t.struct(
        {
            "businessType": t.string(),
            "regionCode": t.string().optional(),
            "places": t.proxy(renames["PlacesOut"]).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ServiceAreaBusinessOut"])
    types["MoreHoursTypeIn"] = t.struct({"_": t.string().optional()}).named(
        renames["MoreHoursTypeIn"]
    )
    types["MoreHoursTypeOut"] = t.struct(
        {
            "localizedDisplayName": t.string().optional(),
            "hoursTypeId": t.string().optional(),
            "displayName": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["MoreHoursTypeOut"])
    types["TimePeriodIn"] = t.struct(
        {
            "openTime": t.proxy(renames["TimeOfDayIn"]),
            "closeTime": t.proxy(renames["TimeOfDayIn"]),
            "closeDay": t.string(),
            "openDay": t.string(),
        }
    ).named(renames["TimePeriodIn"])
    types["TimePeriodOut"] = t.struct(
        {
            "openTime": t.proxy(renames["TimeOfDayOut"]),
            "closeTime": t.proxy(renames["TimeOfDayOut"]),
            "closeDay": t.string(),
            "openDay": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["TimePeriodOut"])
    types["ProfileIn"] = t.struct({"description": t.string()}).named(
        renames["ProfileIn"]
    )
    types["ProfileOut"] = t.struct(
        {
            "description": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ProfileOut"])
    types["GoogleUpdatedLocationIn"] = t.struct(
        {
            "pendingMask": t.string().optional(),
            "diffMask": t.string().optional(),
            "location": t.proxy(renames["LocationIn"]).optional(),
        }
    ).named(renames["GoogleUpdatedLocationIn"])
    types["GoogleUpdatedLocationOut"] = t.struct(
        {
            "pendingMask": t.string().optional(),
            "diffMask": t.string().optional(),
            "location": t.proxy(renames["LocationOut"]).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["GoogleUpdatedLocationOut"])
    types["TimeOfDayIn"] = t.struct(
        {
            "nanos": t.integer().optional(),
            "minutes": t.integer().optional(),
            "hours": t.integer().optional(),
            "seconds": t.integer().optional(),
        }
    ).named(renames["TimeOfDayIn"])
    types["TimeOfDayOut"] = t.struct(
        {
            "nanos": t.integer().optional(),
            "minutes": t.integer().optional(),
            "hours": t.integer().optional(),
            "seconds": t.integer().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["TimeOfDayOut"])
    types["ClearLocationAssociationRequestIn"] = t.struct(
        {"_": t.string().optional()}
    ).named(renames["ClearLocationAssociationRequestIn"])
    types["ClearLocationAssociationRequestOut"] = t.struct(
        {"error": t.proxy(renames["ErrorResponse"]).optional()}
    ).named(renames["ClearLocationAssociationRequestOut"])
    types["LocationIn"] = t.struct(
        {
            "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
            "name": t.string().optional(),
            "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
            "latlng": t.proxy(renames["LatLngIn"]).optional(),
            "labels": t.array(t.string()).optional(),
            "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
            "categories": t.proxy(renames["CategoriesIn"]).optional(),
            "websiteUri": t.string().optional(),
            "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
            "profile": t.proxy(renames["ProfileIn"]).optional(),
            "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
            "title": t.string(),
            "storeCode": t.string().optional(),
            "languageCode": t.string().optional(),
            "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
            "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
            "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
            "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
            "adWordsLocationExtensions": t.proxy(
                renames["AdWordsLocationExtensionsIn"]
            ).optional(),
        }
    ).named(renames["LocationIn"])
    types["LocationOut"] = t.struct(
        {
            "moreHours": t.array(t.proxy(renames["MoreHoursOut"])).optional(),
            "name": t.string().optional(),
            "serviceArea": t.proxy(renames["ServiceAreaBusinessOut"]).optional(),
            "latlng": t.proxy(renames["LatLngOut"]).optional(),
            "labels": t.array(t.string()).optional(),
            "storefrontAddress": t.proxy(renames["PostalAddressOut"]).optional(),
            "categories": t.proxy(renames["CategoriesOut"]).optional(),
            "websiteUri": t.string().optional(),
            "relationshipData": t.proxy(renames["RelationshipDataOut"]).optional(),
            "profile": t.proxy(renames["ProfileOut"]).optional(),
            "phoneNumbers": t.proxy(renames["PhoneNumbersOut"]).optional(),
            "title": t.string(),
            "metadata": t.proxy(renames["MetadataOut"]).optional(),
            "storeCode": t.string().optional(),
            "languageCode": t.string().optional(),
            "serviceItems": t.array(t.proxy(renames["ServiceItemOut"])).optional(),
            "regularHours": t.proxy(renames["BusinessHoursOut"]).optional(),
            "openInfo": t.proxy(renames["OpenInfoOut"]).optional(),
            "specialHours": t.proxy(renames["SpecialHoursOut"]).optional(),
            "adWordsLocationExtensions": t.proxy(
                renames["AdWordsLocationExtensionsOut"]
            ).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["LocationOut"])
    types["ListCategoriesResponseIn"] = t.struct(
        {
            "categories": t.array(t.proxy(renames["CategoryIn"])).optional(),
            "nextPageToken": t.string().optional(),
        }
    ).named(renames["ListCategoriesResponseIn"])
    types["ListCategoriesResponseOut"] = t.struct(
        {
            "categories": t.array(t.proxy(renames["CategoryOut"])).optional(),
            "nextPageToken": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ListCategoriesResponseOut"])
    types["ServiceTypeIn"] = t.struct({"_": t.string().optional()}).named(
        renames["ServiceTypeIn"]
    )
    types["ServiceTypeOut"] = t.struct(
        {
            "displayName": t.string().optional(),
            "serviceTypeId": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ServiceTypeOut"])
    types["GoogleLocationIn"] = t.struct(
        {
            "requestAdminRightsUri": t.string().optional(),
            "name": t.string().optional(),
            "location": t.proxy(renames["LocationIn"]).optional(),
        }
    ).named(renames["GoogleLocationIn"])
    types["GoogleLocationOut"] = t.struct(
        {
            "requestAdminRightsUri": t.string().optional(),
            "name": t.string().optional(),
            "location": t.proxy(renames["LocationOut"]).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["GoogleLocationOut"])
    types["AdWordsLocationExtensionsIn"] = t.struct({"adPhone": t.string()}).named(
        renames["AdWordsLocationExtensionsIn"]
    )
    types["AdWordsLocationExtensionsOut"] = t.struct(
        {"adPhone": t.string(), "error": t.proxy(renames["ErrorResponse"]).optional()}
    ).named(renames["AdWordsLocationExtensionsOut"])
    types["AttributeMetadataIn"] = t.struct(
        {
            "repeatable": t.boolean().optional(),
            "displayName": t.string().optional(),
            "parent": t.string().optional(),
            "groupDisplayName": t.string().optional(),
            "valueMetadata": t.array(
                t.proxy(renames["AttributeValueMetadataIn"])
            ).optional(),
            "deprecated": t.boolean().optional(),
            "valueType": t.string().optional(),
        }
    ).named(renames["AttributeMetadataIn"])
    types["AttributeMetadataOut"] = t.struct(
        {
            "repeatable": t.boolean().optional(),
            "displayName": t.string().optional(),
            "parent": t.string().optional(),
            "groupDisplayName": t.string().optional(),
            "valueMetadata": t.array(
                t.proxy(renames["AttributeValueMetadataOut"])
            ).optional(),
            "deprecated": t.boolean().optional(),
            "valueType": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AttributeMetadataOut"])
    types["ChainUriIn"] = t.struct({"uri": t.string().optional()}).named(
        renames["ChainUriIn"]
    )
    types["ChainUriOut"] = t.struct(
        {
            "uri": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ChainUriOut"])
    types["RelationshipDataIn"] = t.struct(
        {
            "parentChain": t.string().optional(),
            "parentLocation": t.proxy(renames["RelevantLocationIn"]).optional(),
            "childrenLocations": t.array(
                t.proxy(renames["RelevantLocationIn"])
            ).optional(),
        }
    ).named(renames["RelationshipDataIn"])
    types["RelationshipDataOut"] = t.struct(
        {
            "parentChain": t.string().optional(),
            "parentLocation": t.proxy(renames["RelevantLocationOut"]).optional(),
            "childrenLocations": t.array(
                t.proxy(renames["RelevantLocationOut"])
            ).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["RelationshipDataOut"])
    types["ChainIn"] = t.struct(
        {
            "chainNames": t.array(t.proxy(renames["ChainNameIn"])).optional(),
            "name": t.string(),
            "locationCount": t.integer().optional(),
            "websites": t.array(t.proxy(renames["ChainUriIn"])).optional(),
        }
    ).named(renames["ChainIn"])
    types["ChainOut"] = t.struct(
        {
            "chainNames": t.array(t.proxy(renames["ChainNameOut"])).optional(),
            "name": t.string(),
            "locationCount": t.integer().optional(),
            "websites": t.array(t.proxy(renames["ChainUriOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ChainOut"])
    types["FreeFormServiceItemIn"] = t.struct(
        {"label": t.proxy(renames["LabelIn"]), "category": t.string()}
    ).named(renames["FreeFormServiceItemIn"])
    types["FreeFormServiceItemOut"] = t.struct(
        {
            "label": t.proxy(renames["LabelOut"]),
            "category": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["FreeFormServiceItemOut"])
    types["SpecialHourPeriodIn"] = t.struct(
        {
            "startDate": t.proxy(renames["DateIn"]),
            "closeTime": t.proxy(renames["TimeOfDayIn"]).optional(),
            "endDate": t.proxy(renames["DateIn"]).optional(),
            "closed": t.boolean().optional(),
            "openTime": t.proxy(renames["TimeOfDayIn"]).optional(),
        }
    ).named(renames["SpecialHourPeriodIn"])
    types["SpecialHourPeriodOut"] = t.struct(
        {
            "startDate": t.proxy(renames["DateOut"]),
            "closeTime": t.proxy(renames["TimeOfDayOut"]).optional(),
            "endDate": t.proxy(renames["DateOut"]).optional(),
            "closed": t.boolean().optional(),
            "openTime": t.proxy(renames["TimeOfDayOut"]).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SpecialHourPeriodOut"])
    types["SearchChainsResponseIn"] = t.struct(
        {"chains": t.array(t.proxy(renames["ChainIn"])).optional()}
    ).named(renames["SearchChainsResponseIn"])
    types["SearchChainsResponseOut"] = t.struct(
        {
            "chains": t.array(t.proxy(renames["ChainOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SearchChainsResponseOut"])
    types["BusinessHoursIn"] = t.struct(
        {"periods": t.array(t.proxy(renames["TimePeriodIn"]))}
    ).named(renames["BusinessHoursIn"])
    types["BusinessHoursOut"] = t.struct(
        {
            "periods": t.array(t.proxy(renames["TimePeriodOut"])),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["BusinessHoursOut"])
    types["AttributesIn"] = t.struct(
        {
            "name": t.string(),
            "attributes": t.array(t.proxy(renames["AttributeIn"])).optional(),
        }
    ).named(renames["AttributesIn"])
    types["AttributesOut"] = t.struct(
        {
            "name": t.string(),
            "attributes": t.array(t.proxy(renames["AttributeOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AttributesOut"])
    types["ListAttributeMetadataResponseIn"] = t.struct(
        {
            "attributeMetadata": t.array(
                t.proxy(renames["AttributeMetadataIn"])
            ).optional(),
            "nextPageToken": t.string().optional(),
        }
    ).named(renames["ListAttributeMetadataResponseIn"])
    types["ListAttributeMetadataResponseOut"] = t.struct(
        {
            "attributeMetadata": t.array(
                t.proxy(renames["AttributeMetadataOut"])
            ).optional(),
            "nextPageToken": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ListAttributeMetadataResponseOut"])
    types["PlacesIn"] = t.struct(
        {"placeInfos": t.array(t.proxy(renames["PlaceInfoIn"])).optional()}
    ).named(renames["PlacesIn"])
    types["PlacesOut"] = t.struct(
        {
            "placeInfos": t.array(t.proxy(renames["PlaceInfoOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["PlacesOut"])
    types["BatchGetCategoriesResponseIn"] = t.struct(
        {"categories": t.array(t.proxy(renames["CategoryIn"])).optional()}
    ).named(renames["BatchGetCategoriesResponseIn"])
    types["BatchGetCategoriesResponseOut"] = t.struct(
        {
            "categories": t.array(t.proxy(renames["CategoryOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["BatchGetCategoriesResponseOut"])
    types["DateIn"] = t.struct(
        {
            "year": t.integer().optional(),
            "day": t.integer().optional(),
            "month": t.integer().optional(),
        }
    ).named(renames["DateIn"])
    types["DateOut"] = t.struct(
        {
            "year": t.integer().optional(),
            "day": t.integer().optional(),
            "month": t.integer().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["DateOut"])
    types["SearchGoogleLocationsResponseIn"] = t.struct(
        {"googleLocations": t.array(t.proxy(renames["GoogleLocationIn"])).optional()}
    ).named(renames["SearchGoogleLocationsResponseIn"])
    types["SearchGoogleLocationsResponseOut"] = t.struct(
        {
            "googleLocations": t.array(
                t.proxy(renames["GoogleLocationOut"])
            ).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SearchGoogleLocationsResponseOut"])
    types["RelevantLocationIn"] = t.struct(
        {"relationType": t.string(), "placeId": t.string()}
    ).named(renames["RelevantLocationIn"])
    types["RelevantLocationOut"] = t.struct(
        {
            "relationType": t.string(),
            "placeId": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["RelevantLocationOut"])
    types["ListLocationsResponseIn"] = t.struct(
        {
            "locations": t.array(t.proxy(renames["LocationIn"])).optional(),
            "totalSize": t.integer().optional(),
            "nextPageToken": t.string().optional(),
        }
    ).named(renames["ListLocationsResponseIn"])
    types["ListLocationsResponseOut"] = t.struct(
        {
            "locations": t.array(t.proxy(renames["LocationOut"])).optional(),
            "totalSize": t.integer().optional(),
            "nextPageToken": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ListLocationsResponseOut"])

    functions = {}
    functions["accountsLocationsList"] = googleapi.post(
        "v1/{parent}/locations",
        t.struct(
            {
                "parent": t.string(),
                "requestId": t.string().optional(),
                "validateOnly": t.boolean().optional(),
                "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
                "name": t.string().optional(),
                "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
                "latlng": t.proxy(renames["LatLngIn"]).optional(),
                "labels": t.array(t.string()).optional(),
                "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
                "categories": t.proxy(renames["CategoriesIn"]).optional(),
                "websiteUri": t.string().optional(),
                "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
                "profile": t.proxy(renames["ProfileIn"]).optional(),
                "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
                "title": t.string(),
                "storeCode": t.string().optional(),
                "languageCode": t.string().optional(),
                "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
                "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
                "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
                "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
                "adWordsLocationExtensions": t.proxy(
                    renames["AdWordsLocationExtensionsIn"]
                ).optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["accountsLocationsCreate"] = googleapi.post(
        "v1/{parent}/locations",
        t.struct(
            {
                "parent": t.string(),
                "requestId": t.string().optional(),
                "validateOnly": t.boolean().optional(),
                "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
                "name": t.string().optional(),
                "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
                "latlng": t.proxy(renames["LatLngIn"]).optional(),
                "labels": t.array(t.string()).optional(),
                "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
                "categories": t.proxy(renames["CategoriesIn"]).optional(),
                "websiteUri": t.string().optional(),
                "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
                "profile": t.proxy(renames["ProfileIn"]).optional(),
                "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
                "title": t.string(),
                "storeCode": t.string().optional(),
                "languageCode": t.string().optional(),
                "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
                "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
                "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
                "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
                "adWordsLocationExtensions": t.proxy(
                    renames["AdWordsLocationExtensionsIn"]
                ).optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["googleLocationsSearch"] = googleapi.post(
        "v1/googleLocations:search",
        t.struct(
            {
                "location": t.proxy(renames["LocationIn"]).optional(),
                "pageSize": t.integer().optional(),
                "query": t.string().optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["SearchGoogleLocationsResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsAssociate"] = googleapi.get(
        "v1/{name}:getGoogleUpdated",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["GoogleUpdatedLocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsDelete"] = googleapi.get(
        "v1/{name}:getGoogleUpdated",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["GoogleUpdatedLocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsGetAttributes"] = googleapi.get(
        "v1/{name}:getGoogleUpdated",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["GoogleUpdatedLocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsGet"] = googleapi.get(
        "v1/{name}:getGoogleUpdated",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["GoogleUpdatedLocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsUpdateAttributes"] = googleapi.get(
        "v1/{name}:getGoogleUpdated",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["GoogleUpdatedLocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsClearLocationAssociation"] = googleapi.get(
        "v1/{name}:getGoogleUpdated",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["GoogleUpdatedLocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsPatch"] = googleapi.get(
        "v1/{name}:getGoogleUpdated",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["GoogleUpdatedLocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsGetGoogleUpdated"] = googleapi.get(
        "v1/{name}:getGoogleUpdated",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["GoogleUpdatedLocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsAttributesGetGoogleUpdated"] = googleapi.get(
        "v1/{name}:getGoogleUpdated",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["AttributesOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["attributesList"] = googleapi.get(
        "v1/attributes",
        t.struct(
            {
                "parent": t.string().optional(),
                "pageSize": t.integer().optional(),
                "pageToken": t.string().optional(),
                "regionCode": t.string().optional(),
                "languageCode": t.string().optional(),
                "showAll": t.boolean().optional(),
                "categoryName": t.string().optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["ListAttributeMetadataResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["chainsGet"] = googleapi.get(
        "v1/chains:search",
        t.struct(
            {
                "pageSize": t.integer().optional(),
                "chainName": t.string(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["SearchChainsResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["chainsSearch"] = googleapi.get(
        "v1/chains:search",
        t.struct(
            {
                "pageSize": t.integer().optional(),
                "chainName": t.string(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["SearchChainsResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["categoriesList"] = googleapi.get(
        "v1/categories:batchGet",
        t.struct(
            {
                "names": t.string(),
                "languageCode": t.string(),
                "view": t.string(),
                "regionCode": t.string().optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["BatchGetCategoriesResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["categoriesBatchGet"] = googleapi.get(
        "v1/categories:batchGet",
        t.struct(
            {
                "names": t.string(),
                "languageCode": t.string(),
                "view": t.string(),
                "regionCode": t.string().optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["BatchGetCategoriesResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )

    return Import(
        importer="googleapi",
        renames=renames,
        types=Box(types),
        functions=Box(functions),
    )


# Function generated by GoogleDiscoveryImporter. Do not change.
def import_mybusiness():
    mybusiness = HTTPRuntime("https://mybusinessbusinessinformation.googleapis.com/")

    renames = {
        "ErrorResponse": "_mybusiness_1_ErrorResponse",
        "SearchGoogleLocationsRequestIn": "_mybusiness_2_SearchGoogleLocationsRequestIn",
        "SearchGoogleLocationsRequestOut": "_mybusiness_3_SearchGoogleLocationsRequestOut",
        "LatLngIn": "_mybusiness_4_LatLngIn",
        "LatLngOut": "_mybusiness_5_LatLngOut",
        "RelationshipDataIn": "_mybusiness_6_RelationshipDataIn",
        "RelationshipDataOut": "_mybusiness_7_RelationshipDataOut",
        "GoogleUpdatedLocationIn": "_mybusiness_8_GoogleUpdatedLocationIn",
        "GoogleUpdatedLocationOut": "_mybusiness_9_GoogleUpdatedLocationOut",
        "LabelIn": "_mybusiness_10_LabelIn",
        "LabelOut": "_mybusiness_11_LabelOut",
        "UriAttributeValueIn": "_mybusiness_12_UriAttributeValueIn",
        "UriAttributeValueOut": "_mybusiness_13_UriAttributeValueOut",
        "PhoneNumbersIn": "_mybusiness_14_PhoneNumbersIn",
        "PhoneNumbersOut": "_mybusiness_15_PhoneNumbersOut",
        "AttributesIn": "_mybusiness_16_AttributesIn",
        "AttributesOut": "_mybusiness_17_AttributesOut",
        "FreeFormServiceItemIn": "_mybusiness_18_FreeFormServiceItemIn",
        "FreeFormServiceItemOut": "_mybusiness_19_FreeFormServiceItemOut",
        "EmptyIn": "_mybusiness_20_EmptyIn",
        "EmptyOut": "_mybusiness_21_EmptyOut",
        "StructuredServiceItemIn": "_mybusiness_22_StructuredServiceItemIn",
        "StructuredServiceItemOut": "_mybusiness_23_StructuredServiceItemOut",
        "AttributeMetadataIn": "_mybusiness_24_AttributeMetadataIn",
        "AttributeMetadataOut": "_mybusiness_25_AttributeMetadataOut",
        "SearchChainsResponseIn": "_mybusiness_26_SearchChainsResponseIn",
        "SearchChainsResponseOut": "_mybusiness_27_SearchChainsResponseOut",
        "LocationIn": "_mybusiness_28_LocationIn",
        "LocationOut": "_mybusiness_29_LocationOut",
        "ProfileIn": "_mybusiness_30_ProfileIn",
        "ProfileOut": "_mybusiness_31_ProfileOut",
        "RelevantLocationIn": "_mybusiness_32_RelevantLocationIn",
        "RelevantLocationOut": "_mybusiness_33_RelevantLocationOut",
        "ListAttributeMetadataResponseIn": "_mybusiness_34_ListAttributeMetadataResponseIn",
        "ListAttributeMetadataResponseOut": "_mybusiness_35_ListAttributeMetadataResponseOut",
        "ListCategoriesResponseIn": "_mybusiness_36_ListCategoriesResponseIn",
        "ListCategoriesResponseOut": "_mybusiness_37_ListCategoriesResponseOut",
        "PlaceInfoIn": "_mybusiness_38_PlaceInfoIn",
        "PlaceInfoOut": "_mybusiness_39_PlaceInfoOut",
        "GoogleLocationIn": "_mybusiness_40_GoogleLocationIn",
        "GoogleLocationOut": "_mybusiness_41_GoogleLocationOut",
        "MoneyIn": "_mybusiness_42_MoneyIn",
        "MoneyOut": "_mybusiness_43_MoneyOut",
        "AttributeValueMetadataIn": "_mybusiness_44_AttributeValueMetadataIn",
        "AttributeValueMetadataOut": "_mybusiness_45_AttributeValueMetadataOut",
        "AssociateLocationRequestIn": "_mybusiness_46_AssociateLocationRequestIn",
        "AssociateLocationRequestOut": "_mybusiness_47_AssociateLocationRequestOut",
        "ServiceTypeIn": "_mybusiness_48_ServiceTypeIn",
        "ServiceTypeOut": "_mybusiness_49_ServiceTypeOut",
        "PlacesIn": "_mybusiness_50_PlacesIn",
        "PlacesOut": "_mybusiness_51_PlacesOut",
        "MoreHoursIn": "_mybusiness_52_MoreHoursIn",
        "MoreHoursOut": "_mybusiness_53_MoreHoursOut",
        "PostalAddressIn": "_mybusiness_54_PostalAddressIn",
        "PostalAddressOut": "_mybusiness_55_PostalAddressOut",
        "CategoriesIn": "_mybusiness_56_CategoriesIn",
        "CategoriesOut": "_mybusiness_57_CategoriesOut",
        "ServiceItemIn": "_mybusiness_58_ServiceItemIn",
        "ServiceItemOut": "_mybusiness_59_ServiceItemOut",
        "AttributeIn": "_mybusiness_60_AttributeIn",
        "AttributeOut": "_mybusiness_61_AttributeOut",
        "AdWordsLocationExtensionsIn": "_mybusiness_62_AdWordsLocationExtensionsIn",
        "AdWordsLocationExtensionsOut": "_mybusiness_63_AdWordsLocationExtensionsOut",
        "OpenInfoIn": "_mybusiness_64_OpenInfoIn",
        "OpenInfoOut": "_mybusiness_65_OpenInfoOut",
        "ChainUriIn": "_mybusiness_66_ChainUriIn",
        "ChainUriOut": "_mybusiness_67_ChainUriOut",
        "ServiceAreaBusinessIn": "_mybusiness_68_ServiceAreaBusinessIn",
        "ServiceAreaBusinessOut": "_mybusiness_69_ServiceAreaBusinessOut",
        "BusinessHoursIn": "_mybusiness_70_BusinessHoursIn",
        "BusinessHoursOut": "_mybusiness_71_BusinessHoursOut",
        "TimeOfDayIn": "_mybusiness_72_TimeOfDayIn",
        "TimeOfDayOut": "_mybusiness_73_TimeOfDayOut",
        "DateIn": "_mybusiness_74_DateIn",
        "DateOut": "_mybusiness_75_DateOut",
        "SearchGoogleLocationsResponseIn": "_mybusiness_76_SearchGoogleLocationsResponseIn",
        "SearchGoogleLocationsResponseOut": "_mybusiness_77_SearchGoogleLocationsResponseOut",
        "SpecialHoursIn": "_mybusiness_78_SpecialHoursIn",
        "SpecialHoursOut": "_mybusiness_79_SpecialHoursOut",
        "SpecialHourPeriodIn": "_mybusiness_80_SpecialHourPeriodIn",
        "SpecialHourPeriodOut": "_mybusiness_81_SpecialHourPeriodOut",
        "TimePeriodIn": "_mybusiness_82_TimePeriodIn",
        "TimePeriodOut": "_mybusiness_83_TimePeriodOut",
        "CategoryIn": "_mybusiness_84_CategoryIn",
        "CategoryOut": "_mybusiness_85_CategoryOut",
        "MoreHoursTypeIn": "_mybusiness_86_MoreHoursTypeIn",
        "MoreHoursTypeOut": "_mybusiness_87_MoreHoursTypeOut",
        "ChainIn": "_mybusiness_88_ChainIn",
        "ChainOut": "_mybusiness_89_ChainOut",
        "MetadataIn": "_mybusiness_90_MetadataIn",
        "MetadataOut": "_mybusiness_91_MetadataOut",
        "ChainNameIn": "_mybusiness_92_ChainNameIn",
        "ChainNameOut": "_mybusiness_93_ChainNameOut",
        "BatchGetCategoriesResponseIn": "_mybusiness_94_BatchGetCategoriesResponseIn",
        "BatchGetCategoriesResponseOut": "_mybusiness_95_BatchGetCategoriesResponseOut",
        "RepeatedEnumAttributeValueIn": "_mybusiness_96_RepeatedEnumAttributeValueIn",
        "RepeatedEnumAttributeValueOut": "_mybusiness_97_RepeatedEnumAttributeValueOut",
        "ClearLocationAssociationRequestIn": "_mybusiness_98_ClearLocationAssociationRequestIn",
        "ClearLocationAssociationRequestOut": "_mybusiness_99_ClearLocationAssociationRequestOut",
        "ListLocationsResponseIn": "_mybusiness_100_ListLocationsResponseIn",
        "ListLocationsResponseOut": "_mybusiness_101_ListLocationsResponseOut",
    }

    types = {}
    types["ErrorResponse"] = t.struct(
        {"code": t.integer(), "message": t.string(), "status": t.string()}
    ).named(renames["ErrorResponse"])
    types["SearchGoogleLocationsRequestIn"] = t.struct(
        {
            "query": t.string().optional(),
            "pageSize": t.integer().optional(),
            "location": t.proxy(renames["LocationIn"]).optional(),
        }
    ).named(renames["SearchGoogleLocationsRequestIn"])
    types["SearchGoogleLocationsRequestOut"] = t.struct(
        {
            "query": t.string().optional(),
            "pageSize": t.integer().optional(),
            "location": t.proxy(renames["LocationOut"]).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SearchGoogleLocationsRequestOut"])
    types["LatLngIn"] = t.struct(
        {"latitude": t.number().optional(), "longitude": t.number().optional()}
    ).named(renames["LatLngIn"])
    types["LatLngOut"] = t.struct(
        {
            "latitude": t.number().optional(),
            "longitude": t.number().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["LatLngOut"])
    types["RelationshipDataIn"] = t.struct(
        {
            "parentLocation": t.proxy(renames["RelevantLocationIn"]).optional(),
            "childrenLocations": t.array(
                t.proxy(renames["RelevantLocationIn"])
            ).optional(),
            "parentChain": t.string().optional(),
        }
    ).named(renames["RelationshipDataIn"])
    types["RelationshipDataOut"] = t.struct(
        {
            "parentLocation": t.proxy(renames["RelevantLocationOut"]).optional(),
            "childrenLocations": t.array(
                t.proxy(renames["RelevantLocationOut"])
            ).optional(),
            "parentChain": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["RelationshipDataOut"])
    types["GoogleUpdatedLocationIn"] = t.struct(
        {
            "location": t.proxy(renames["LocationIn"]).optional(),
            "diffMask": t.string().optional(),
            "pendingMask": t.string().optional(),
        }
    ).named(renames["GoogleUpdatedLocationIn"])
    types["GoogleUpdatedLocationOut"] = t.struct(
        {
            "location": t.proxy(renames["LocationOut"]).optional(),
            "diffMask": t.string().optional(),
            "pendingMask": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["GoogleUpdatedLocationOut"])
    types["LabelIn"] = t.struct(
        {
            "displayName": t.string(),
            "description": t.string().optional(),
            "languageCode": t.string().optional(),
        }
    ).named(renames["LabelIn"])
    types["LabelOut"] = t.struct(
        {
            "displayName": t.string(),
            "description": t.string().optional(),
            "languageCode": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["LabelOut"])
    types["UriAttributeValueIn"] = t.struct({"uri": t.string()}).named(
        renames["UriAttributeValueIn"]
    )
    types["UriAttributeValueOut"] = t.struct(
        {"uri": t.string(), "error": t.proxy(renames["ErrorResponse"]).optional()}
    ).named(renames["UriAttributeValueOut"])
    types["PhoneNumbersIn"] = t.struct(
        {"additionalPhones": t.array(t.string()).optional(), "primaryPhone": t.string()}
    ).named(renames["PhoneNumbersIn"])
    types["PhoneNumbersOut"] = t.struct(
        {
            "additionalPhones": t.array(t.string()).optional(),
            "primaryPhone": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["PhoneNumbersOut"])
    types["AttributesIn"] = t.struct(
        {
            "attributes": t.array(t.proxy(renames["AttributeIn"])).optional(),
            "name": t.string(),
        }
    ).named(renames["AttributesIn"])
    types["AttributesOut"] = t.struct(
        {
            "attributes": t.array(t.proxy(renames["AttributeOut"])).optional(),
            "name": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AttributesOut"])
    types["FreeFormServiceItemIn"] = t.struct(
        {"category": t.string(), "label": t.proxy(renames["LabelIn"])}
    ).named(renames["FreeFormServiceItemIn"])
    types["FreeFormServiceItemOut"] = t.struct(
        {
            "category": t.string(),
            "label": t.proxy(renames["LabelOut"]),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["FreeFormServiceItemOut"])
    types["EmptyIn"] = t.struct({"_": t.string().optional()}).named(renames["EmptyIn"])
    types["EmptyOut"] = t.struct(
        {"error": t.proxy(renames["ErrorResponse"]).optional()}
    ).named(renames["EmptyOut"])
    types["StructuredServiceItemIn"] = t.struct(
        {"serviceTypeId": t.string(), "description": t.string().optional()}
    ).named(renames["StructuredServiceItemIn"])
    types["StructuredServiceItemOut"] = t.struct(
        {
            "serviceTypeId": t.string(),
            "description": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["StructuredServiceItemOut"])
    types["AttributeMetadataIn"] = t.struct(
        {
            "displayName": t.string().optional(),
            "valueMetadata": t.array(
                t.proxy(renames["AttributeValueMetadataIn"])
            ).optional(),
            "repeatable": t.boolean().optional(),
            "deprecated": t.boolean().optional(),
            "valueType": t.string().optional(),
            "parent": t.string().optional(),
            "groupDisplayName": t.string().optional(),
        }
    ).named(renames["AttributeMetadataIn"])
    types["AttributeMetadataOut"] = t.struct(
        {
            "displayName": t.string().optional(),
            "valueMetadata": t.array(
                t.proxy(renames["AttributeValueMetadataOut"])
            ).optional(),
            "repeatable": t.boolean().optional(),
            "deprecated": t.boolean().optional(),
            "valueType": t.string().optional(),
            "parent": t.string().optional(),
            "groupDisplayName": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AttributeMetadataOut"])
    types["SearchChainsResponseIn"] = t.struct(
        {"chains": t.array(t.proxy(renames["ChainIn"])).optional()}
    ).named(renames["SearchChainsResponseIn"])
    types["SearchChainsResponseOut"] = t.struct(
        {
            "chains": t.array(t.proxy(renames["ChainOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SearchChainsResponseOut"])
    types["LocationIn"] = t.struct(
        {
            "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
            "languageCode": t.string().optional(),
            "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
            "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
            "labels": t.array(t.string()).optional(),
            "latlng": t.proxy(renames["LatLngIn"]).optional(),
            "profile": t.proxy(renames["ProfileIn"]).optional(),
            "name": t.string().optional(),
            "websiteUri": t.string().optional(),
            "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
            "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
            "title": t.string(),
            "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
            "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
            "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
            "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
            "storeCode": t.string().optional(),
            "adWordsLocationExtensions": t.proxy(
                renames["AdWordsLocationExtensionsIn"]
            ).optional(),
            "categories": t.proxy(renames["CategoriesIn"]).optional(),
        }
    ).named(renames["LocationIn"])
    types["LocationOut"] = t.struct(
        {
            "serviceArea": t.proxy(renames["ServiceAreaBusinessOut"]).optional(),
            "languageCode": t.string().optional(),
            "storefrontAddress": t.proxy(renames["PostalAddressOut"]).optional(),
            "serviceItems": t.array(t.proxy(renames["ServiceItemOut"])).optional(),
            "metadata": t.proxy(renames["MetadataOut"]).optional(),
            "labels": t.array(t.string()).optional(),
            "latlng": t.proxy(renames["LatLngOut"]).optional(),
            "profile": t.proxy(renames["ProfileOut"]).optional(),
            "name": t.string().optional(),
            "websiteUri": t.string().optional(),
            "phoneNumbers": t.proxy(renames["PhoneNumbersOut"]).optional(),
            "specialHours": t.proxy(renames["SpecialHoursOut"]).optional(),
            "title": t.string(),
            "openInfo": t.proxy(renames["OpenInfoOut"]).optional(),
            "regularHours": t.proxy(renames["BusinessHoursOut"]).optional(),
            "relationshipData": t.proxy(renames["RelationshipDataOut"]).optional(),
            "moreHours": t.array(t.proxy(renames["MoreHoursOut"])).optional(),
            "storeCode": t.string().optional(),
            "adWordsLocationExtensions": t.proxy(
                renames["AdWordsLocationExtensionsOut"]
            ).optional(),
            "categories": t.proxy(renames["CategoriesOut"]).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["LocationOut"])
    types["ProfileIn"] = t.struct({"description": t.string()}).named(
        renames["ProfileIn"]
    )
    types["ProfileOut"] = t.struct(
        {
            "description": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ProfileOut"])
    types["RelevantLocationIn"] = t.struct(
        {"placeId": t.string(), "relationType": t.string()}
    ).named(renames["RelevantLocationIn"])
    types["RelevantLocationOut"] = t.struct(
        {
            "placeId": t.string(),
            "relationType": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["RelevantLocationOut"])
    types["ListAttributeMetadataResponseIn"] = t.struct(
        {
            "nextPageToken": t.string().optional(),
            "attributeMetadata": t.array(
                t.proxy(renames["AttributeMetadataIn"])
            ).optional(),
        }
    ).named(renames["ListAttributeMetadataResponseIn"])
    types["ListAttributeMetadataResponseOut"] = t.struct(
        {
            "nextPageToken": t.string().optional(),
            "attributeMetadata": t.array(
                t.proxy(renames["AttributeMetadataOut"])
            ).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ListAttributeMetadataResponseOut"])
    types["ListCategoriesResponseIn"] = t.struct(
        {
            "nextPageToken": t.string().optional(),
            "categories": t.array(t.proxy(renames["CategoryIn"])).optional(),
        }
    ).named(renames["ListCategoriesResponseIn"])
    types["ListCategoriesResponseOut"] = t.struct(
        {
            "nextPageToken": t.string().optional(),
            "categories": t.array(t.proxy(renames["CategoryOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ListCategoriesResponseOut"])
    types["PlaceInfoIn"] = t.struct(
        {"placeId": t.string(), "placeName": t.string()}
    ).named(renames["PlaceInfoIn"])
    types["PlaceInfoOut"] = t.struct(
        {
            "placeId": t.string(),
            "placeName": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["PlaceInfoOut"])
    types["GoogleLocationIn"] = t.struct(
        {
            "location": t.proxy(renames["LocationIn"]).optional(),
            "requestAdminRightsUri": t.string().optional(),
            "name": t.string().optional(),
        }
    ).named(renames["GoogleLocationIn"])
    types["GoogleLocationOut"] = t.struct(
        {
            "location": t.proxy(renames["LocationOut"]).optional(),
            "requestAdminRightsUri": t.string().optional(),
            "name": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["GoogleLocationOut"])
    types["MoneyIn"] = t.struct(
        {
            "units": t.string().optional(),
            "currencyCode": t.string().optional(),
            "nanos": t.integer().optional(),
        }
    ).named(renames["MoneyIn"])
    types["MoneyOut"] = t.struct(
        {
            "units": t.string().optional(),
            "currencyCode": t.string().optional(),
            "nanos": t.integer().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["MoneyOut"])
    types["AttributeValueMetadataIn"] = t.struct(
        {
            "value": t.struct({"_": t.string().optional()}).optional(),
            "displayName": t.string().optional(),
        }
    ).named(renames["AttributeValueMetadataIn"])
    types["AttributeValueMetadataOut"] = t.struct(
        {
            "value": t.struct({"_": t.string().optional()}).optional(),
            "displayName": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AttributeValueMetadataOut"])
    types["AssociateLocationRequestIn"] = t.struct(
        {"placeId": t.string().optional()}
    ).named(renames["AssociateLocationRequestIn"])
    types["AssociateLocationRequestOut"] = t.struct(
        {
            "placeId": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AssociateLocationRequestOut"])
    types["ServiceTypeIn"] = t.struct({"_": t.string().optional()}).named(
        renames["ServiceTypeIn"]
    )
    types["ServiceTypeOut"] = t.struct(
        {
            "serviceTypeId": t.string().optional(),
            "displayName": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ServiceTypeOut"])
    types["PlacesIn"] = t.struct(
        {"placeInfos": t.array(t.proxy(renames["PlaceInfoIn"])).optional()}
    ).named(renames["PlacesIn"])
    types["PlacesOut"] = t.struct(
        {
            "placeInfos": t.array(t.proxy(renames["PlaceInfoOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["PlacesOut"])
    types["MoreHoursIn"] = t.struct(
        {
            "periods": t.array(t.proxy(renames["TimePeriodIn"])),
            "hoursTypeId": t.string(),
        }
    ).named(renames["MoreHoursIn"])
    types["MoreHoursOut"] = t.struct(
        {
            "periods": t.array(t.proxy(renames["TimePeriodOut"])),
            "hoursTypeId": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["MoreHoursOut"])
    types["PostalAddressIn"] = t.struct(
        {
            "sortingCode": t.string().optional(),
            "recipients": t.array(t.string()).optional(),
            "administrativeArea": t.string().optional(),
            "regionCode": t.string(),
            "addressLines": t.array(t.string()).optional(),
            "locality": t.string().optional(),
            "sublocality": t.string().optional(),
            "languageCode": t.string().optional(),
            "postalCode": t.string().optional(),
            "organization": t.string().optional(),
            "revision": t.integer().optional(),
        }
    ).named(renames["PostalAddressIn"])
    types["PostalAddressOut"] = t.struct(
        {
            "sortingCode": t.string().optional(),
            "recipients": t.array(t.string()).optional(),
            "administrativeArea": t.string().optional(),
            "regionCode": t.string(),
            "addressLines": t.array(t.string()).optional(),
            "locality": t.string().optional(),
            "sublocality": t.string().optional(),
            "languageCode": t.string().optional(),
            "postalCode": t.string().optional(),
            "organization": t.string().optional(),
            "revision": t.integer().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["PostalAddressOut"])
    types["CategoriesIn"] = t.struct(
        {
            "additionalCategories": t.array(t.proxy(renames["CategoryIn"])).optional(),
            "primaryCategory": t.proxy(renames["CategoryIn"]),
        }
    ).named(renames["CategoriesIn"])
    types["CategoriesOut"] = t.struct(
        {
            "additionalCategories": t.array(t.proxy(renames["CategoryOut"])).optional(),
            "primaryCategory": t.proxy(renames["CategoryOut"]),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["CategoriesOut"])
    types["ServiceItemIn"] = t.struct(
        {
            "structuredServiceItem": t.proxy(
                renames["StructuredServiceItemIn"]
            ).optional(),
            "freeFormServiceItem": t.proxy(renames["FreeFormServiceItemIn"]).optional(),
            "price": t.proxy(renames["MoneyIn"]).optional(),
        }
    ).named(renames["ServiceItemIn"])
    types["ServiceItemOut"] = t.struct(
        {
            "structuredServiceItem": t.proxy(
                renames["StructuredServiceItemOut"]
            ).optional(),
            "freeFormServiceItem": t.proxy(
                renames["FreeFormServiceItemOut"]
            ).optional(),
            "price": t.proxy(renames["MoneyOut"]).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ServiceItemOut"])
    types["AttributeIn"] = t.struct(
        {
            "repeatedEnumValue": t.proxy(
                renames["RepeatedEnumAttributeValueIn"]
            ).optional(),
            "uriValues": t.array(t.proxy(renames["UriAttributeValueIn"])).optional(),
            "values": t.array(t.struct({"_": t.string().optional()})).optional(),
            "name": t.string(),
        }
    ).named(renames["AttributeIn"])
    types["AttributeOut"] = t.struct(
        {
            "repeatedEnumValue": t.proxy(
                renames["RepeatedEnumAttributeValueOut"]
            ).optional(),
            "valueType": t.string().optional(),
            "uriValues": t.array(t.proxy(renames["UriAttributeValueOut"])).optional(),
            "values": t.array(t.struct({"_": t.string().optional()})).optional(),
            "name": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["AttributeOut"])
    types["AdWordsLocationExtensionsIn"] = t.struct({"adPhone": t.string()}).named(
        renames["AdWordsLocationExtensionsIn"]
    )
    types["AdWordsLocationExtensionsOut"] = t.struct(
        {"adPhone": t.string(), "error": t.proxy(renames["ErrorResponse"]).optional()}
    ).named(renames["AdWordsLocationExtensionsOut"])
    types["OpenInfoIn"] = t.struct(
        {"status": t.string(), "openingDate": t.proxy(renames["DateIn"]).optional()}
    ).named(renames["OpenInfoIn"])
    types["OpenInfoOut"] = t.struct(
        {
            "status": t.string(),
            "openingDate": t.proxy(renames["DateOut"]).optional(),
            "canReopen": t.boolean().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["OpenInfoOut"])
    types["ChainUriIn"] = t.struct({"uri": t.string().optional()}).named(
        renames["ChainUriIn"]
    )
    types["ChainUriOut"] = t.struct(
        {
            "uri": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ChainUriOut"])
    types["ServiceAreaBusinessIn"] = t.struct(
        {
            "places": t.proxy(renames["PlacesIn"]).optional(),
            "regionCode": t.string().optional(),
            "businessType": t.string(),
        }
    ).named(renames["ServiceAreaBusinessIn"])
    types["ServiceAreaBusinessOut"] = t.struct(
        {
            "places": t.proxy(renames["PlacesOut"]).optional(),
            "regionCode": t.string().optional(),
            "businessType": t.string(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ServiceAreaBusinessOut"])
    types["BusinessHoursIn"] = t.struct(
        {"periods": t.array(t.proxy(renames["TimePeriodIn"]))}
    ).named(renames["BusinessHoursIn"])
    types["BusinessHoursOut"] = t.struct(
        {
            "periods": t.array(t.proxy(renames["TimePeriodOut"])),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["BusinessHoursOut"])
    types["TimeOfDayIn"] = t.struct(
        {
            "nanos": t.integer().optional(),
            "seconds": t.integer().optional(),
            "minutes": t.integer().optional(),
            "hours": t.integer().optional(),
        }
    ).named(renames["TimeOfDayIn"])
    types["TimeOfDayOut"] = t.struct(
        {
            "nanos": t.integer().optional(),
            "seconds": t.integer().optional(),
            "minutes": t.integer().optional(),
            "hours": t.integer().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["TimeOfDayOut"])
    types["DateIn"] = t.struct(
        {
            "month": t.integer().optional(),
            "day": t.integer().optional(),
            "year": t.integer().optional(),
        }
    ).named(renames["DateIn"])
    types["DateOut"] = t.struct(
        {
            "month": t.integer().optional(),
            "day": t.integer().optional(),
            "year": t.integer().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["DateOut"])
    types["SearchGoogleLocationsResponseIn"] = t.struct(
        {"googleLocations": t.array(t.proxy(renames["GoogleLocationIn"])).optional()}
    ).named(renames["SearchGoogleLocationsResponseIn"])
    types["SearchGoogleLocationsResponseOut"] = t.struct(
        {
            "googleLocations": t.array(
                t.proxy(renames["GoogleLocationOut"])
            ).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SearchGoogleLocationsResponseOut"])
    types["SpecialHoursIn"] = t.struct(
        {"specialHourPeriods": t.array(t.proxy(renames["SpecialHourPeriodIn"]))}
    ).named(renames["SpecialHoursIn"])
    types["SpecialHoursOut"] = t.struct(
        {
            "specialHourPeriods": t.array(t.proxy(renames["SpecialHourPeriodOut"])),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SpecialHoursOut"])
    types["SpecialHourPeriodIn"] = t.struct(
        {
            "closeTime": t.proxy(renames["TimeOfDayIn"]).optional(),
            "closed": t.boolean().optional(),
            "startDate": t.proxy(renames["DateIn"]),
            "openTime": t.proxy(renames["TimeOfDayIn"]).optional(),
            "endDate": t.proxy(renames["DateIn"]).optional(),
        }
    ).named(renames["SpecialHourPeriodIn"])
    types["SpecialHourPeriodOut"] = t.struct(
        {
            "closeTime": t.proxy(renames["TimeOfDayOut"]).optional(),
            "closed": t.boolean().optional(),
            "startDate": t.proxy(renames["DateOut"]),
            "openTime": t.proxy(renames["TimeOfDayOut"]).optional(),
            "endDate": t.proxy(renames["DateOut"]).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["SpecialHourPeriodOut"])
    types["TimePeriodIn"] = t.struct(
        {
            "openDay": t.string(),
            "closeTime": t.proxy(renames["TimeOfDayIn"]),
            "closeDay": t.string(),
            "openTime": t.proxy(renames["TimeOfDayIn"]),
        }
    ).named(renames["TimePeriodIn"])
    types["TimePeriodOut"] = t.struct(
        {
            "openDay": t.string(),
            "closeTime": t.proxy(renames["TimeOfDayOut"]),
            "closeDay": t.string(),
            "openTime": t.proxy(renames["TimeOfDayOut"]),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["TimePeriodOut"])
    types["CategoryIn"] = t.struct({"name": t.string()}).named(renames["CategoryIn"])
    types["CategoryOut"] = t.struct(
        {
            "name": t.string(),
            "displayName": t.string().optional(),
            "moreHoursTypes": t.array(t.proxy(renames["MoreHoursTypeOut"])).optional(),
            "serviceTypes": t.array(t.proxy(renames["ServiceTypeOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["CategoryOut"])
    types["MoreHoursTypeIn"] = t.struct({"_": t.string().optional()}).named(
        renames["MoreHoursTypeIn"]
    )
    types["MoreHoursTypeOut"] = t.struct(
        {
            "displayName": t.string().optional(),
            "hoursTypeId": t.string().optional(),
            "localizedDisplayName": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["MoreHoursTypeOut"])
    types["ChainIn"] = t.struct(
        {
            "websites": t.array(t.proxy(renames["ChainUriIn"])).optional(),
            "name": t.string(),
            "locationCount": t.integer().optional(),
            "chainNames": t.array(t.proxy(renames["ChainNameIn"])).optional(),
        }
    ).named(renames["ChainIn"])
    types["ChainOut"] = t.struct(
        {
            "websites": t.array(t.proxy(renames["ChainUriOut"])).optional(),
            "name": t.string(),
            "locationCount": t.integer().optional(),
            "chainNames": t.array(t.proxy(renames["ChainNameOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ChainOut"])
    types["MetadataIn"] = t.struct({"_": t.string().optional()}).named(
        renames["MetadataIn"]
    )
    types["MetadataOut"] = t.struct(
        {
            "canOperateLodgingData": t.boolean().optional(),
            "hasGoogleUpdated": t.boolean().optional(),
            "canHaveFoodMenus": t.boolean().optional(),
            "hasPendingEdits": t.boolean().optional(),
            "canOperateLocalPost": t.boolean().optional(),
            "hasVoiceOfMerchant": t.boolean().optional(),
            "duplicateLocation": t.string().optional(),
            "mapsUri": t.string().optional(),
            "placeId": t.string().optional(),
            "canHaveBusinessCalls": t.boolean().optional(),
            "canModifyServiceList": t.boolean().optional(),
            "newReviewUri": t.string().optional(),
            "canOperateHealthData": t.boolean().optional(),
            "canDelete": t.boolean().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["MetadataOut"])
    types["ChainNameIn"] = t.struct(
        {"languageCode": t.string().optional(), "displayName": t.string().optional()}
    ).named(renames["ChainNameIn"])
    types["ChainNameOut"] = t.struct(
        {
            "languageCode": t.string().optional(),
            "displayName": t.string().optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ChainNameOut"])
    types["BatchGetCategoriesResponseIn"] = t.struct(
        {"categories": t.array(t.proxy(renames["CategoryIn"])).optional()}
    ).named(renames["BatchGetCategoriesResponseIn"])
    types["BatchGetCategoriesResponseOut"] = t.struct(
        {
            "categories": t.array(t.proxy(renames["CategoryOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["BatchGetCategoriesResponseOut"])
    types["RepeatedEnumAttributeValueIn"] = t.struct(
        {
            "unsetValues": t.array(t.string()).optional(),
            "setValues": t.array(t.string()).optional(),
        }
    ).named(renames["RepeatedEnumAttributeValueIn"])
    types["RepeatedEnumAttributeValueOut"] = t.struct(
        {
            "unsetValues": t.array(t.string()).optional(),
            "setValues": t.array(t.string()).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["RepeatedEnumAttributeValueOut"])
    types["ClearLocationAssociationRequestIn"] = t.struct(
        {"_": t.string().optional()}
    ).named(renames["ClearLocationAssociationRequestIn"])
    types["ClearLocationAssociationRequestOut"] = t.struct(
        {"error": t.proxy(renames["ErrorResponse"]).optional()}
    ).named(renames["ClearLocationAssociationRequestOut"])
    types["ListLocationsResponseIn"] = t.struct(
        {
            "nextPageToken": t.string().optional(),
            "totalSize": t.integer().optional(),
            "locations": t.array(t.proxy(renames["LocationIn"])).optional(),
        }
    ).named(renames["ListLocationsResponseIn"])
    types["ListLocationsResponseOut"] = t.struct(
        {
            "nextPageToken": t.string().optional(),
            "totalSize": t.integer().optional(),
            "locations": t.array(t.proxy(renames["LocationOut"])).optional(),
            "error": t.proxy(renames["ErrorResponse"]).optional(),
        }
    ).named(renames["ListLocationsResponseOut"])

    functions = {}
    functions["locationsGetGoogleUpdated"] = mybusiness.get(
        "v1/{name}",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsDelete"] = mybusiness.get(
        "v1/{name}",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsUpdateAttributes"] = mybusiness.get(
        "v1/{name}",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsAssociate"] = mybusiness.get(
        "v1/{name}",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsGetAttributes"] = mybusiness.get(
        "v1/{name}",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsClearLocationAssociation"] = mybusiness.get(
        "v1/{name}",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsPatch"] = mybusiness.get(
        "v1/{name}",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsGet"] = mybusiness.get(
        "v1/{name}",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["locationsAttributesGetGoogleUpdated"] = mybusiness.get(
        "v1/{name}:getGoogleUpdated",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["AttributesOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["chainsSearch"] = mybusiness.get(
        "v1/{name}",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["ChainOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["chainsGet"] = mybusiness.get(
        "v1/{name}",
        t.struct({"name": t.string(), "auth": t.string().optional()}),
        t.proxy(renames["ChainOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["accountsLocationsList"] = mybusiness.post(
        "v1/{parent}/locations",
        t.struct(
            {
                "parent": t.string(),
                "validateOnly": t.boolean().optional(),
                "requestId": t.string().optional(),
                "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
                "languageCode": t.string().optional(),
                "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
                "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
                "labels": t.array(t.string()).optional(),
                "latlng": t.proxy(renames["LatLngIn"]).optional(),
                "profile": t.proxy(renames["ProfileIn"]).optional(),
                "name": t.string().optional(),
                "websiteUri": t.string().optional(),
                "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
                "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
                "title": t.string(),
                "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
                "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
                "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
                "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
                "storeCode": t.string().optional(),
                "adWordsLocationExtensions": t.proxy(
                    renames["AdWordsLocationExtensionsIn"]
                ).optional(),
                "categories": t.proxy(renames["CategoriesIn"]).optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["accountsLocationsCreate"] = mybusiness.post(
        "v1/{parent}/locations",
        t.struct(
            {
                "parent": t.string(),
                "validateOnly": t.boolean().optional(),
                "requestId": t.string().optional(),
                "serviceArea": t.proxy(renames["ServiceAreaBusinessIn"]).optional(),
                "languageCode": t.string().optional(),
                "storefrontAddress": t.proxy(renames["PostalAddressIn"]).optional(),
                "serviceItems": t.array(t.proxy(renames["ServiceItemIn"])).optional(),
                "labels": t.array(t.string()).optional(),
                "latlng": t.proxy(renames["LatLngIn"]).optional(),
                "profile": t.proxy(renames["ProfileIn"]).optional(),
                "name": t.string().optional(),
                "websiteUri": t.string().optional(),
                "phoneNumbers": t.proxy(renames["PhoneNumbersIn"]).optional(),
                "specialHours": t.proxy(renames["SpecialHoursIn"]).optional(),
                "title": t.string(),
                "openInfo": t.proxy(renames["OpenInfoIn"]).optional(),
                "regularHours": t.proxy(renames["BusinessHoursIn"]).optional(),
                "relationshipData": t.proxy(renames["RelationshipDataIn"]).optional(),
                "moreHours": t.array(t.proxy(renames["MoreHoursIn"])).optional(),
                "storeCode": t.string().optional(),
                "adWordsLocationExtensions": t.proxy(
                    renames["AdWordsLocationExtensionsIn"]
                ).optional(),
                "categories": t.proxy(renames["CategoriesIn"]).optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["LocationOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["categoriesList"] = mybusiness.get(
        "v1/categories:batchGet",
        t.struct(
            {
                "view": t.string(),
                "regionCode": t.string().optional(),
                "languageCode": t.string(),
                "names": t.string(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["BatchGetCategoriesResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["categoriesBatchGet"] = mybusiness.get(
        "v1/categories:batchGet",
        t.struct(
            {
                "view": t.string(),
                "regionCode": t.string().optional(),
                "languageCode": t.string(),
                "names": t.string(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["BatchGetCategoriesResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["attributesList"] = mybusiness.get(
        "v1/attributes",
        t.struct(
            {
                "showAll": t.boolean().optional(),
                "regionCode": t.string().optional(),
                "languageCode": t.string().optional(),
                "categoryName": t.string().optional(),
                "pageSize": t.integer().optional(),
                "pageToken": t.string().optional(),
                "parent": t.string().optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["ListAttributeMetadataResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )
    functions["googleLocationsSearch"] = mybusiness.post(
        "v1/googleLocations:search",
        t.struct(
            {
                "query": t.string().optional(),
                "pageSize": t.integer().optional(),
                "location": t.proxy(renames["LocationIn"]).optional(),
                "auth": t.string().optional(),
            }
        ),
        t.proxy(renames["SearchGoogleLocationsResponseOut"]),
        auth_token_field="auth",
        content_type="application/json",
    )

    return Import(
        importer="mybusiness",
        renames=renames,
        types=Box(types),
        functions=Box(functions),
    )


with TypeGraph(name="mybusinessbusinessinformation") as g:
    googleapi = import_googleapi()
    public = policies.public()
    g.expose(**{name: f.add_policy(public) for name, f in googleapi.functions.items()})
