*

!tools/*.ts
!tools/tasks/
!tools/LICENSE-Elastic-2.0.md

!src/common
!src/meta-cli/Cargo.toml
!src/metagen/Cargo.toml
!src/metagen/src/fdk_rust/static/Cargo.toml
!src/mt_deno
!src/pyrt_wit_wire
!src/typegate/
!src/typegraph/core/
!src/wit/
!src/xtask/Cargo.toml

!examples/deno.jsonc
!src/typegraph/deno/deno.json
!tests/deno.jsonc

!deno.jsonc
!deno.lock
!import_map.json

!ghjk.ts
!Cargo.toml
!Cargo.lock
