name: linear ticket check
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Check comment issues
        working-directory: tools/linear-checker
        run: npm install && npm run check
